// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: appearances.proto

package appproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PLAYER_ACTION int32

const (
	PLAYER_ACTION_PLAYER_ACTION_NONE               PLAYER_ACTION = 0
	PLAYER_ACTION_PLAYER_ACTION_LOOK               PLAYER_ACTION = 1
	PLAYER_ACTION_PLAYER_ACTION_USE                PLAYER_ACTION = 2
	PLAYER_ACTION_PLAYER_ACTION_OPEN               PLAYER_ACTION = 3
	PLAYER_ACTION_PLAYER_ACTION_AUTOWALK_HIGHLIGHT PLAYER_ACTION = 4
)

// Enum value maps for PLAYER_ACTION.
var (
	PLAYER_ACTION_name = map[int32]string{
		0: "PLAYER_ACTION_NONE",
		1: "PLAYER_ACTION_LOOK",
		2: "PLAYER_ACTION_USE",
		3: "PLAYER_ACTION_OPEN",
		4: "PLAYER_ACTION_AUTOWALK_HIGHLIGHT",
	}
	PLAYER_ACTION_value = map[string]int32{
		"PLAYER_ACTION_NONE":               0,
		"PLAYER_ACTION_LOOK":               1,
		"PLAYER_ACTION_USE":                2,
		"PLAYER_ACTION_OPEN":               3,
		"PLAYER_ACTION_AUTOWALK_HIGHLIGHT": 4,
	}
)

func (x PLAYER_ACTION) Enum() *PLAYER_ACTION {
	p := new(PLAYER_ACTION)
	*p = x
	return p
}

func (x PLAYER_ACTION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PLAYER_ACTION) Descriptor() protoreflect.EnumDescriptor {
	return file_appearances_proto_enumTypes[0].Descriptor()
}

func (PLAYER_ACTION) Type() protoreflect.EnumType {
	return &file_appearances_proto_enumTypes[0]
}

func (x PLAYER_ACTION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PLAYER_ACTION) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PLAYER_ACTION(num)
	return nil
}

// Deprecated: Use PLAYER_ACTION.Descriptor instead.
func (PLAYER_ACTION) EnumDescriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{0}
}

type ITEM_CATEGORY int32

const (
	ITEM_CATEGORY_ITEM_CATEGORY_ARMORS            ITEM_CATEGORY = 1
	ITEM_CATEGORY_ITEM_CATEGORY_AMULETS           ITEM_CATEGORY = 2
	ITEM_CATEGORY_ITEM_CATEGORY_BOOTS             ITEM_CATEGORY = 3
	ITEM_CATEGORY_ITEM_CATEGORY_CONTAINERS        ITEM_CATEGORY = 4
	ITEM_CATEGORY_ITEM_CATEGORY_DECORATION        ITEM_CATEGORY = 5
	ITEM_CATEGORY_ITEM_CATEGORY_FOOD              ITEM_CATEGORY = 6
	ITEM_CATEGORY_ITEM_CATEGORY_HELMETS_HATS      ITEM_CATEGORY = 7
	ITEM_CATEGORY_ITEM_CATEGORY_LEGS              ITEM_CATEGORY = 8
	ITEM_CATEGORY_ITEM_CATEGORY_OTHERS            ITEM_CATEGORY = 9
	ITEM_CATEGORY_ITEM_CATEGORY_POTIONS           ITEM_CATEGORY = 10
	ITEM_CATEGORY_ITEM_CATEGORY_RINGS             ITEM_CATEGORY = 11
	ITEM_CATEGORY_ITEM_CATEGORY_RUNES             ITEM_CATEGORY = 12
	ITEM_CATEGORY_ITEM_CATEGORY_SHIELDS           ITEM_CATEGORY = 13
	ITEM_CATEGORY_ITEM_CATEGORY_TOOLS             ITEM_CATEGORY = 14
	ITEM_CATEGORY_ITEM_CATEGORY_VALUABLES         ITEM_CATEGORY = 15
	ITEM_CATEGORY_ITEM_CATEGORY_AMMUNITION        ITEM_CATEGORY = 16
	ITEM_CATEGORY_ITEM_CATEGORY_AXES              ITEM_CATEGORY = 17
	ITEM_CATEGORY_ITEM_CATEGORY_CLUBS             ITEM_CATEGORY = 18
	ITEM_CATEGORY_ITEM_CATEGORY_DISTANCE_WEAPONS  ITEM_CATEGORY = 19
	ITEM_CATEGORY_ITEM_CATEGORY_SWORDS            ITEM_CATEGORY = 20
	ITEM_CATEGORY_ITEM_CATEGORY_WANDS_RODS        ITEM_CATEGORY = 21
	ITEM_CATEGORY_ITEM_CATEGORY_PREMIUM_SCROLLS   ITEM_CATEGORY = 22
	ITEM_CATEGORY_ITEM_CATEGORY_TIBIA_COINS       ITEM_CATEGORY = 23
	ITEM_CATEGORY_ITEM_CATEGORY_CREATURE_PRODUCTS ITEM_CATEGORY = 24
	ITEM_CATEGORY_ITEM_CATEGORY_QUIVER            ITEM_CATEGORY = 25
	ITEM_CATEGORY_ITEM_CATEGORY_TWOHANDWEAPON     ITEM_CATEGORY = 26
	ITEM_CATEGORY_ITEM_CATEGORY_FIST_WEAPONS      ITEM_CATEGORY = 27
	ITEM_CATEGORY_ITEM_CATEGORY_BACKPACK          ITEM_CATEGORY = 28
	ITEM_CATEGORY_ITEM_CATEGORY_ONEHANDWEAPON     ITEM_CATEGORY = 29
	ITEM_CATEGORY_ITEM_CATEGORY_ARROW             ITEM_CATEGORY = 30
	ITEM_CATEGORY_ITEM_CATEGORY_SOULCORES         ITEM_CATEGORY = 31
)

// Enum value maps for ITEM_CATEGORY.
var (
	ITEM_CATEGORY_name = map[int32]string{
		1:  "ITEM_CATEGORY_ARMORS",
		2:  "ITEM_CATEGORY_AMULETS",
		3:  "ITEM_CATEGORY_BOOTS",
		4:  "ITEM_CATEGORY_CONTAINERS",
		5:  "ITEM_CATEGORY_DECORATION",
		6:  "ITEM_CATEGORY_FOOD",
		7:  "ITEM_CATEGORY_HELMETS_HATS",
		8:  "ITEM_CATEGORY_LEGS",
		9:  "ITEM_CATEGORY_OTHERS",
		10: "ITEM_CATEGORY_POTIONS",
		11: "ITEM_CATEGORY_RINGS",
		12: "ITEM_CATEGORY_RUNES",
		13: "ITEM_CATEGORY_SHIELDS",
		14: "ITEM_CATEGORY_TOOLS",
		15: "ITEM_CATEGORY_VALUABLES",
		16: "ITEM_CATEGORY_AMMUNITION",
		17: "ITEM_CATEGORY_AXES",
		18: "ITEM_CATEGORY_CLUBS",
		19: "ITEM_CATEGORY_DISTANCE_WEAPONS",
		20: "ITEM_CATEGORY_SWORDS",
		21: "ITEM_CATEGORY_WANDS_RODS",
		22: "ITEM_CATEGORY_PREMIUM_SCROLLS",
		23: "ITEM_CATEGORY_TIBIA_COINS",
		24: "ITEM_CATEGORY_CREATURE_PRODUCTS",
		25: "ITEM_CATEGORY_QUIVER",
		26: "ITEM_CATEGORY_TWOHANDWEAPON",
		27: "ITEM_CATEGORY_FIST_WEAPONS",
		28: "ITEM_CATEGORY_BACKPACK",
		29: "ITEM_CATEGORY_ONEHANDWEAPON",
		30: "ITEM_CATEGORY_ARROW",
		31: "ITEM_CATEGORY_SOULCORES",
	}
	ITEM_CATEGORY_value = map[string]int32{
		"ITEM_CATEGORY_ARMORS":            1,
		"ITEM_CATEGORY_AMULETS":           2,
		"ITEM_CATEGORY_BOOTS":             3,
		"ITEM_CATEGORY_CONTAINERS":        4,
		"ITEM_CATEGORY_DECORATION":        5,
		"ITEM_CATEGORY_FOOD":              6,
		"ITEM_CATEGORY_HELMETS_HATS":      7,
		"ITEM_CATEGORY_LEGS":              8,
		"ITEM_CATEGORY_OTHERS":            9,
		"ITEM_CATEGORY_POTIONS":           10,
		"ITEM_CATEGORY_RINGS":             11,
		"ITEM_CATEGORY_RUNES":             12,
		"ITEM_CATEGORY_SHIELDS":           13,
		"ITEM_CATEGORY_TOOLS":             14,
		"ITEM_CATEGORY_VALUABLES":         15,
		"ITEM_CATEGORY_AMMUNITION":        16,
		"ITEM_CATEGORY_AXES":              17,
		"ITEM_CATEGORY_CLUBS":             18,
		"ITEM_CATEGORY_DISTANCE_WEAPONS":  19,
		"ITEM_CATEGORY_SWORDS":            20,
		"ITEM_CATEGORY_WANDS_RODS":        21,
		"ITEM_CATEGORY_PREMIUM_SCROLLS":   22,
		"ITEM_CATEGORY_TIBIA_COINS":       23,
		"ITEM_CATEGORY_CREATURE_PRODUCTS": 24,
		"ITEM_CATEGORY_QUIVER":            25,
		"ITEM_CATEGORY_TWOHANDWEAPON":     26,
		"ITEM_CATEGORY_FIST_WEAPONS":      27,
		"ITEM_CATEGORY_BACKPACK":          28,
		"ITEM_CATEGORY_ONEHANDWEAPON":     29,
		"ITEM_CATEGORY_ARROW":             30,
		"ITEM_CATEGORY_SOULCORES":         31,
	}
)

func (x ITEM_CATEGORY) Enum() *ITEM_CATEGORY {
	p := new(ITEM_CATEGORY)
	*p = x
	return p
}

func (x ITEM_CATEGORY) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ITEM_CATEGORY) Descriptor() protoreflect.EnumDescriptor {
	return file_appearances_proto_enumTypes[1].Descriptor()
}

func (ITEM_CATEGORY) Type() protoreflect.EnumType {
	return &file_appearances_proto_enumTypes[1]
}

func (x ITEM_CATEGORY) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ITEM_CATEGORY) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ITEM_CATEGORY(num)
	return nil
}

// Deprecated: Use ITEM_CATEGORY.Descriptor instead.
func (ITEM_CATEGORY) EnumDescriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{1}
}

type PLAYER_PROFESSION int32

const (
	PLAYER_PROFESSION_PLAYER_PROFESSION_ANY      PLAYER_PROFESSION = -1
	PLAYER_PROFESSION_PLAYER_PROFESSION_NONE     PLAYER_PROFESSION = 0
	PLAYER_PROFESSION_PLAYER_PROFESSION_KNIGHT   PLAYER_PROFESSION = 1
	PLAYER_PROFESSION_PLAYER_PROFESSION_PALADIN  PLAYER_PROFESSION = 2
	PLAYER_PROFESSION_PLAYER_PROFESSION_SORCERER PLAYER_PROFESSION = 3
	PLAYER_PROFESSION_PLAYER_PROFESSION_DRUID    PLAYER_PROFESSION = 4
	PLAYER_PROFESSION_PLAYER_PROFESSION_MONK     PLAYER_PROFESSION = 5
	PLAYER_PROFESSION_PLAYER_PROFESSION_PROMOTED PLAYER_PROFESSION = 10
)

// Enum value maps for PLAYER_PROFESSION.
var (
	PLAYER_PROFESSION_name = map[int32]string{
		-1: "PLAYER_PROFESSION_ANY",
		0:  "PLAYER_PROFESSION_NONE",
		1:  "PLAYER_PROFESSION_KNIGHT",
		2:  "PLAYER_PROFESSION_PALADIN",
		3:  "PLAYER_PROFESSION_SORCERER",
		4:  "PLAYER_PROFESSION_DRUID",
		5:  "PLAYER_PROFESSION_MONK",
		10: "PLAYER_PROFESSION_PROMOTED",
	}
	PLAYER_PROFESSION_value = map[string]int32{
		"PLAYER_PROFESSION_ANY":      -1,
		"PLAYER_PROFESSION_NONE":     0,
		"PLAYER_PROFESSION_KNIGHT":   1,
		"PLAYER_PROFESSION_PALADIN":  2,
		"PLAYER_PROFESSION_SORCERER": 3,
		"PLAYER_PROFESSION_DRUID":    4,
		"PLAYER_PROFESSION_MONK":     5,
		"PLAYER_PROFESSION_PROMOTED": 10,
	}
)

func (x PLAYER_PROFESSION) Enum() *PLAYER_PROFESSION {
	p := new(PLAYER_PROFESSION)
	*p = x
	return p
}

func (x PLAYER_PROFESSION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PLAYER_PROFESSION) Descriptor() protoreflect.EnumDescriptor {
	return file_appearances_proto_enumTypes[2].Descriptor()
}

func (PLAYER_PROFESSION) Type() protoreflect.EnumType {
	return &file_appearances_proto_enumTypes[2]
}

func (x PLAYER_PROFESSION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PLAYER_PROFESSION) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PLAYER_PROFESSION(num)
	return nil
}

// Deprecated: Use PLAYER_PROFESSION.Descriptor instead.
func (PLAYER_PROFESSION) EnumDescriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{2}
}

type ANIMATION_LOOP_TYPE int32

const (
	ANIMATION_LOOP_TYPE_ANIMATION_LOOP_TYPE_PINGPONG ANIMATION_LOOP_TYPE = -1
	ANIMATION_LOOP_TYPE_ANIMATION_LOOP_TYPE_INFINITE ANIMATION_LOOP_TYPE = 0
	ANIMATION_LOOP_TYPE_ANIMATION_LOOP_TYPE_COUNTED  ANIMATION_LOOP_TYPE = 1
)

// Enum value maps for ANIMATION_LOOP_TYPE.
var (
	ANIMATION_LOOP_TYPE_name = map[int32]string{
		-1: "ANIMATION_LOOP_TYPE_PINGPONG",
		0:  "ANIMATION_LOOP_TYPE_INFINITE",
		1:  "ANIMATION_LOOP_TYPE_COUNTED",
	}
	ANIMATION_LOOP_TYPE_value = map[string]int32{
		"ANIMATION_LOOP_TYPE_PINGPONG": -1,
		"ANIMATION_LOOP_TYPE_INFINITE": 0,
		"ANIMATION_LOOP_TYPE_COUNTED":  1,
	}
)

func (x ANIMATION_LOOP_TYPE) Enum() *ANIMATION_LOOP_TYPE {
	p := new(ANIMATION_LOOP_TYPE)
	*p = x
	return p
}

func (x ANIMATION_LOOP_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ANIMATION_LOOP_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_appearances_proto_enumTypes[3].Descriptor()
}

func (ANIMATION_LOOP_TYPE) Type() protoreflect.EnumType {
	return &file_appearances_proto_enumTypes[3]
}

func (x ANIMATION_LOOP_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ANIMATION_LOOP_TYPE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ANIMATION_LOOP_TYPE(num)
	return nil
}

// Deprecated: Use ANIMATION_LOOP_TYPE.Descriptor instead.
func (ANIMATION_LOOP_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{3}
}

type HOOK_TYPE int32

const (
	HOOK_TYPE_HOOK_TYPE_SOUTH HOOK_TYPE = 1
	HOOK_TYPE_HOOK_TYPE_EAST  HOOK_TYPE = 2
)

// Enum value maps for HOOK_TYPE.
var (
	HOOK_TYPE_name = map[int32]string{
		1: "HOOK_TYPE_SOUTH",
		2: "HOOK_TYPE_EAST",
	}
	HOOK_TYPE_value = map[string]int32{
		"HOOK_TYPE_SOUTH": 1,
		"HOOK_TYPE_EAST":  2,
	}
)

func (x HOOK_TYPE) Enum() *HOOK_TYPE {
	p := new(HOOK_TYPE)
	*p = x
	return p
}

func (x HOOK_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HOOK_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_appearances_proto_enumTypes[4].Descriptor()
}

func (HOOK_TYPE) Type() protoreflect.EnumType {
	return &file_appearances_proto_enumTypes[4]
}

func (x HOOK_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HOOK_TYPE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HOOK_TYPE(num)
	return nil
}

// Deprecated: Use HOOK_TYPE.Descriptor instead.
func (HOOK_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{4}
}

type FIXED_FRAME_GROUP int32

const (
	FIXED_FRAME_GROUP_FIXED_FRAME_GROUP_OUTFIT_IDLE    FIXED_FRAME_GROUP = 0
	FIXED_FRAME_GROUP_FIXED_FRAME_GROUP_OUTFIT_MOVING  FIXED_FRAME_GROUP = 1
	FIXED_FRAME_GROUP_FIXED_FRAME_GROUP_OBJECT_INITIAL FIXED_FRAME_GROUP = 2
)

// Enum value maps for FIXED_FRAME_GROUP.
var (
	FIXED_FRAME_GROUP_name = map[int32]string{
		0: "FIXED_FRAME_GROUP_OUTFIT_IDLE",
		1: "FIXED_FRAME_GROUP_OUTFIT_MOVING",
		2: "FIXED_FRAME_GROUP_OBJECT_INITIAL",
	}
	FIXED_FRAME_GROUP_value = map[string]int32{
		"FIXED_FRAME_GROUP_OUTFIT_IDLE":    0,
		"FIXED_FRAME_GROUP_OUTFIT_MOVING":  1,
		"FIXED_FRAME_GROUP_OBJECT_INITIAL": 2,
	}
)

func (x FIXED_FRAME_GROUP) Enum() *FIXED_FRAME_GROUP {
	p := new(FIXED_FRAME_GROUP)
	*p = x
	return p
}

func (x FIXED_FRAME_GROUP) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FIXED_FRAME_GROUP) Descriptor() protoreflect.EnumDescriptor {
	return file_appearances_proto_enumTypes[5].Descriptor()
}

func (FIXED_FRAME_GROUP) Type() protoreflect.EnumType {
	return &file_appearances_proto_enumTypes[5]
}

func (x FIXED_FRAME_GROUP) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FIXED_FRAME_GROUP) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FIXED_FRAME_GROUP(num)
	return nil
}

// Deprecated: Use FIXED_FRAME_GROUP.Descriptor instead.
func (FIXED_FRAME_GROUP) EnumDescriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{5}
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *uint32                `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y             *uint32                `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	Z             *uint32                `protobuf:"varint,3,opt,name=z" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_appearances_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetX() uint32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Coordinate) GetY() uint32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Coordinate) GetZ() uint32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

type Appearances struct {
	state                       protoimpl.MessageState       `protogen:"open.v1"`
	Object                      []*Appearance                `protobuf:"bytes,1,rep,name=object" json:"object,omitempty"`
	Outfit                      []*Appearance                `protobuf:"bytes,2,rep,name=outfit" json:"outfit,omitempty"`
	Effect                      []*Appearance                `protobuf:"bytes,3,rep,name=effect" json:"effect,omitempty"`
	Missile                     []*Appearance                `protobuf:"bytes,4,rep,name=missile" json:"missile,omitempty"`
	SpecialMeaningAppearanceIds *SpecialMeaningAppearanceIds `protobuf:"bytes,5,opt,name=special_meaning_appearance_ids,json=specialMeaningAppearanceIds" json:"special_meaning_appearance_ids,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Appearances) Reset() {
	*x = Appearances{}
	mi := &file_appearances_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appearances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appearances) ProtoMessage() {}

func (x *Appearances) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appearances.ProtoReflect.Descriptor instead.
func (*Appearances) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{1}
}

func (x *Appearances) GetObject() []*Appearance {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Appearances) GetOutfit() []*Appearance {
	if x != nil {
		return x.Outfit
	}
	return nil
}

func (x *Appearances) GetEffect() []*Appearance {
	if x != nil {
		return x.Effect
	}
	return nil
}

func (x *Appearances) GetMissile() []*Appearance {
	if x != nil {
		return x.Missile
	}
	return nil
}

func (x *Appearances) GetSpecialMeaningAppearanceIds() *SpecialMeaningAppearanceIds {
	if x != nil {
		return x.SpecialMeaningAppearanceIds
	}
	return nil
}

type SpritePhase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationMin   *uint32                `protobuf:"varint,1,opt,name=duration_min,json=durationMin" json:"duration_min,omitempty"`
	DurationMax   *uint32                `protobuf:"varint,2,opt,name=duration_max,json=durationMax" json:"duration_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpritePhase) Reset() {
	*x = SpritePhase{}
	mi := &file_appearances_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpritePhase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpritePhase) ProtoMessage() {}

func (x *SpritePhase) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpritePhase.ProtoReflect.Descriptor instead.
func (*SpritePhase) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{2}
}

func (x *SpritePhase) GetDurationMin() uint32 {
	if x != nil && x.DurationMin != nil {
		return *x.DurationMin
	}
	return 0
}

func (x *SpritePhase) GetDurationMax() uint32 {
	if x != nil && x.DurationMax != nil {
		return *x.DurationMax
	}
	return 0
}

type SpriteAnimation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DefaultStartPhase *uint32                `protobuf:"varint,1,opt,name=default_start_phase,json=defaultStartPhase" json:"default_start_phase,omitempty"`
	Synchronized      *bool                  `protobuf:"varint,2,opt,name=synchronized" json:"synchronized,omitempty"`
	RandomStartPhase  *bool                  `protobuf:"varint,3,opt,name=random_start_phase,json=randomStartPhase" json:"random_start_phase,omitempty"`
	LoopType          *ANIMATION_LOOP_TYPE   `protobuf:"varint,4,opt,name=loop_type,json=loopType,enum=Canary.protobuf.appearances.ANIMATION_LOOP_TYPE" json:"loop_type,omitempty"`
	LoopCount         *uint32                `protobuf:"varint,5,opt,name=loop_count,json=loopCount" json:"loop_count,omitempty"`
	SpritePhase       []*SpritePhase         `protobuf:"bytes,6,rep,name=sprite_phase,json=spritePhase" json:"sprite_phase,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpriteAnimation) Reset() {
	*x = SpriteAnimation{}
	mi := &file_appearances_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpriteAnimation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpriteAnimation) ProtoMessage() {}

func (x *SpriteAnimation) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpriteAnimation.ProtoReflect.Descriptor instead.
func (*SpriteAnimation) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{3}
}

func (x *SpriteAnimation) GetDefaultStartPhase() uint32 {
	if x != nil && x.DefaultStartPhase != nil {
		return *x.DefaultStartPhase
	}
	return 0
}

func (x *SpriteAnimation) GetSynchronized() bool {
	if x != nil && x.Synchronized != nil {
		return *x.Synchronized
	}
	return false
}

func (x *SpriteAnimation) GetRandomStartPhase() bool {
	if x != nil && x.RandomStartPhase != nil {
		return *x.RandomStartPhase
	}
	return false
}

func (x *SpriteAnimation) GetLoopType() ANIMATION_LOOP_TYPE {
	if x != nil && x.LoopType != nil {
		return *x.LoopType
	}
	return ANIMATION_LOOP_TYPE_ANIMATION_LOOP_TYPE_PINGPONG
}

func (x *SpriteAnimation) GetLoopCount() uint32 {
	if x != nil && x.LoopCount != nil {
		return *x.LoopCount
	}
	return 0
}

func (x *SpriteAnimation) GetSpritePhase() []*SpritePhase {
	if x != nil {
		return x.SpritePhase
	}
	return nil
}

type Box struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *uint32                `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y             *uint32                `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	Width         *uint32                `protobuf:"varint,3,opt,name=width" json:"width,omitempty"`
	Height        *uint32                `protobuf:"varint,4,opt,name=height" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Box) Reset() {
	*x = Box{}
	mi := &file_appearances_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Box) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Box) ProtoMessage() {}

func (x *Box) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Box.ProtoReflect.Descriptor instead.
func (*Box) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{4}
}

func (x *Box) GetX() uint32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Box) GetY() uint32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Box) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *Box) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

type SpriteInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	PatternWidth            *uint32                `protobuf:"varint,1,opt,name=pattern_width,json=patternWidth" json:"pattern_width,omitempty"`
	PatternHeight           *uint32                `protobuf:"varint,2,opt,name=pattern_height,json=patternHeight" json:"pattern_height,omitempty"`
	PatternDepth            *uint32                `protobuf:"varint,3,opt,name=pattern_depth,json=patternDepth" json:"pattern_depth,omitempty"`
	Layers                  *uint32                `protobuf:"varint,4,opt,name=layers" json:"layers,omitempty"`
	SpriteId                []uint32               `protobuf:"varint,5,rep,name=sprite_id,json=spriteId" json:"sprite_id,omitempty"`
	BoundingSquare          *uint32                `protobuf:"varint,7,opt,name=bounding_square,json=boundingSquare" json:"bounding_square,omitempty"`
	Animation               *SpriteAnimation       `protobuf:"bytes,6,opt,name=animation" json:"animation,omitempty"`
	IsOpaque                *bool                  `protobuf:"varint,8,opt,name=is_opaque,json=isOpaque" json:"is_opaque,omitempty"`
	BoundingBoxPerDirection []*Box                 `protobuf:"bytes,9,rep,name=bounding_box_per_direction,json=boundingBoxPerDirection" json:"bounding_box_per_direction,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SpriteInfo) Reset() {
	*x = SpriteInfo{}
	mi := &file_appearances_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpriteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpriteInfo) ProtoMessage() {}

func (x *SpriteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpriteInfo.ProtoReflect.Descriptor instead.
func (*SpriteInfo) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{5}
}

func (x *SpriteInfo) GetPatternWidth() uint32 {
	if x != nil && x.PatternWidth != nil {
		return *x.PatternWidth
	}
	return 0
}

func (x *SpriteInfo) GetPatternHeight() uint32 {
	if x != nil && x.PatternHeight != nil {
		return *x.PatternHeight
	}
	return 0
}

func (x *SpriteInfo) GetPatternDepth() uint32 {
	if x != nil && x.PatternDepth != nil {
		return *x.PatternDepth
	}
	return 0
}

func (x *SpriteInfo) GetLayers() uint32 {
	if x != nil && x.Layers != nil {
		return *x.Layers
	}
	return 0
}

func (x *SpriteInfo) GetSpriteId() []uint32 {
	if x != nil {
		return x.SpriteId
	}
	return nil
}

func (x *SpriteInfo) GetBoundingSquare() uint32 {
	if x != nil && x.BoundingSquare != nil {
		return *x.BoundingSquare
	}
	return 0
}

func (x *SpriteInfo) GetAnimation() *SpriteAnimation {
	if x != nil {
		return x.Animation
	}
	return nil
}

func (x *SpriteInfo) GetIsOpaque() bool {
	if x != nil && x.IsOpaque != nil {
		return *x.IsOpaque
	}
	return false
}

func (x *SpriteInfo) GetBoundingBoxPerDirection() []*Box {
	if x != nil {
		return x.BoundingBoxPerDirection
	}
	return nil
}

type FrameGroup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FixedFrameGroup *FIXED_FRAME_GROUP     `protobuf:"varint,1,opt,name=fixed_frame_group,json=fixedFrameGroup,enum=Canary.protobuf.appearances.FIXED_FRAME_GROUP" json:"fixed_frame_group,omitempty"`
	Id              *uint32                `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	SpriteInfo      *SpriteInfo            `protobuf:"bytes,3,opt,name=sprite_info,json=spriteInfo" json:"sprite_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FrameGroup) Reset() {
	*x = FrameGroup{}
	mi := &file_appearances_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameGroup) ProtoMessage() {}

func (x *FrameGroup) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameGroup.ProtoReflect.Descriptor instead.
func (*FrameGroup) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{6}
}

func (x *FrameGroup) GetFixedFrameGroup() FIXED_FRAME_GROUP {
	if x != nil && x.FixedFrameGroup != nil {
		return *x.FixedFrameGroup
	}
	return FIXED_FRAME_GROUP_FIXED_FRAME_GROUP_OUTFIT_IDLE
}

func (x *FrameGroup) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *FrameGroup) GetSpriteInfo() *SpriteInfo {
	if x != nil {
		return x.SpriteInfo
	}
	return nil
}

type Appearance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FrameGroup    []*FrameGroup          `protobuf:"bytes,2,rep,name=frame_group,json=frameGroup" json:"frame_group,omitempty"`
	Flags         *AppearanceFlags       `protobuf:"bytes,3,opt,name=flags" json:"flags,omitempty"`
	Name          []byte                 `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Description   []byte                 `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appearance) Reset() {
	*x = Appearance{}
	mi := &file_appearances_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appearance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appearance) ProtoMessage() {}

func (x *Appearance) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appearance.ProtoReflect.Descriptor instead.
func (*Appearance) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{7}
}

func (x *Appearance) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Appearance) GetFrameGroup() []*FrameGroup {
	if x != nil {
		return x.FrameGroup
	}
	return nil
}

func (x *Appearance) GetFlags() *AppearanceFlags {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *Appearance) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Appearance) GetDescription() []byte {
	if x != nil {
		return x.Description
	}
	return nil
}

type AppearanceFlags struct {
	state                 protoimpl.MessageState               `protogen:"open.v1"`
	Bank                  *AppearanceFlagBank                  `protobuf:"bytes,1,opt,name=bank" json:"bank,omitempty"`
	Clip                  *bool                                `protobuf:"varint,2,opt,name=clip" json:"clip,omitempty"`
	Bottom                *bool                                `protobuf:"varint,3,opt,name=bottom" json:"bottom,omitempty"`
	Top                   *bool                                `protobuf:"varint,4,opt,name=top" json:"top,omitempty"`
	Container             *bool                                `protobuf:"varint,5,opt,name=container" json:"container,omitempty"`
	Cumulative            *bool                                `protobuf:"varint,6,opt,name=cumulative" json:"cumulative,omitempty"`
	Usable                *bool                                `protobuf:"varint,7,opt,name=usable" json:"usable,omitempty"`
	Forceuse              *bool                                `protobuf:"varint,8,opt,name=forceuse" json:"forceuse,omitempty"`
	Multiuse              *bool                                `protobuf:"varint,9,opt,name=multiuse" json:"multiuse,omitempty"`
	Write                 *AppearanceFlagWrite                 `protobuf:"bytes,10,opt,name=write" json:"write,omitempty"`
	WriteOnce             *AppearanceFlagWriteOnce             `protobuf:"bytes,11,opt,name=write_once,json=writeOnce" json:"write_once,omitempty"`
	Liquidpool            *bool                                `protobuf:"varint,12,opt,name=liquidpool" json:"liquidpool,omitempty"`
	Unpass                *bool                                `protobuf:"varint,13,opt,name=unpass" json:"unpass,omitempty"`
	Unmove                *bool                                `protobuf:"varint,14,opt,name=unmove" json:"unmove,omitempty"`
	Unsight               *bool                                `protobuf:"varint,15,opt,name=unsight" json:"unsight,omitempty"`
	Avoid                 *bool                                `protobuf:"varint,16,opt,name=avoid" json:"avoid,omitempty"`
	NoMovementAnimation   *bool                                `protobuf:"varint,17,opt,name=no_movement_animation,json=noMovementAnimation" json:"no_movement_animation,omitempty"`
	Take                  *bool                                `protobuf:"varint,18,opt,name=take" json:"take,omitempty"`
	Liquidcontainer       *bool                                `protobuf:"varint,19,opt,name=liquidcontainer" json:"liquidcontainer,omitempty"`
	Hang                  *bool                                `protobuf:"varint,20,opt,name=hang" json:"hang,omitempty"`
	Hook                  *AppearanceFlagHook                  `protobuf:"bytes,21,opt,name=hook" json:"hook,omitempty"`
	Rotate                *bool                                `protobuf:"varint,22,opt,name=rotate" json:"rotate,omitempty"`
	Light                 *AppearanceFlagLight                 `protobuf:"bytes,23,opt,name=light" json:"light,omitempty"`
	DontHide              *bool                                `protobuf:"varint,24,opt,name=dont_hide,json=dontHide" json:"dont_hide,omitempty"`
	Translucent           *bool                                `protobuf:"varint,25,opt,name=translucent" json:"translucent,omitempty"`
	Shift                 *AppearanceFlagShift                 `protobuf:"bytes,26,opt,name=shift" json:"shift,omitempty"`
	Height                *AppearanceFlagHeight                `protobuf:"bytes,27,opt,name=height" json:"height,omitempty"`
	LyingObject           *bool                                `protobuf:"varint,28,opt,name=lying_object,json=lyingObject" json:"lying_object,omitempty"`
	AnimateAlways         *bool                                `protobuf:"varint,29,opt,name=animate_always,json=animateAlways" json:"animate_always,omitempty"`
	Automap               *AppearanceFlagAutomap               `protobuf:"bytes,30,opt,name=automap" json:"automap,omitempty"`
	Lenshelp              *AppearanceFlagLenshelp              `protobuf:"bytes,31,opt,name=lenshelp" json:"lenshelp,omitempty"`
	Fullbank              *bool                                `protobuf:"varint,32,opt,name=fullbank" json:"fullbank,omitempty"`
	IgnoreLook            *bool                                `protobuf:"varint,33,opt,name=ignore_look,json=ignoreLook" json:"ignore_look,omitempty"`
	Clothes               *AppearanceFlagClothes               `protobuf:"bytes,34,opt,name=clothes" json:"clothes,omitempty"`
	DefaultAction         *AppearanceFlagDefaultAction         `protobuf:"bytes,35,opt,name=default_action,json=defaultAction" json:"default_action,omitempty"`
	Market                *AppearanceFlagMarket                `protobuf:"bytes,36,opt,name=market" json:"market,omitempty"`
	Wrap                  *bool                                `protobuf:"varint,37,opt,name=wrap" json:"wrap,omitempty"`
	Unwrap                *bool                                `protobuf:"varint,38,opt,name=unwrap" json:"unwrap,omitempty"`
	Topeffect             *bool                                `protobuf:"varint,39,opt,name=topeffect" json:"topeffect,omitempty"`
	Npcsaledata           []*AppearanceFlagNPC                 `protobuf:"bytes,40,rep,name=npcsaledata" json:"npcsaledata,omitempty"`
	Changedtoexpire       *AppearanceFlagChangedToExpire       `protobuf:"bytes,41,opt,name=changedtoexpire" json:"changedtoexpire,omitempty"`
	Corpse                *bool                                `protobuf:"varint,42,opt,name=corpse" json:"corpse,omitempty"`
	PlayerCorpse          *bool                                `protobuf:"varint,43,opt,name=player_corpse,json=playerCorpse" json:"player_corpse,omitempty"`
	Cyclopediaitem        *AppearanceFlagCyclopedia            `protobuf:"bytes,44,opt,name=cyclopediaitem" json:"cyclopediaitem,omitempty"`
	Ammo                  *bool                                `protobuf:"varint,45,opt,name=ammo" json:"ammo,omitempty"`
	ShowOffSocket         *bool                                `protobuf:"varint,46,opt,name=show_off_socket,json=showOffSocket" json:"show_off_socket,omitempty"`
	Reportable            *bool                                `protobuf:"varint,47,opt,name=reportable" json:"reportable,omitempty"`
	Upgradeclassification *AppearanceFlagUpgradeClassification `protobuf:"bytes,48,opt,name=upgradeclassification" json:"upgradeclassification,omitempty"`
	ReverseAddonsEast     *bool                                `protobuf:"varint,49,opt,name=reverse_addons_east,json=reverseAddonsEast" json:"reverse_addons_east,omitempty"`
	ReverseAddonsWest     *bool                                `protobuf:"varint,50,opt,name=reverse_addons_west,json=reverseAddonsWest" json:"reverse_addons_west,omitempty"`
	ReverseAddonsSouth    *bool                                `protobuf:"varint,51,opt,name=reverse_addons_south,json=reverseAddonsSouth" json:"reverse_addons_south,omitempty"`
	ReverseAddonsNorth    *bool                                `protobuf:"varint,52,opt,name=reverse_addons_north,json=reverseAddonsNorth" json:"reverse_addons_north,omitempty"`
	Wearout               *bool                                `protobuf:"varint,53,opt,name=wearout" json:"wearout,omitempty"`
	Clockexpire           *bool                                `protobuf:"varint,54,opt,name=clockexpire" json:"clockexpire,omitempty"`
	Expire                *bool                                `protobuf:"varint,55,opt,name=expire" json:"expire,omitempty"`
	Expirestop            *bool                                `protobuf:"varint,56,opt,name=expirestop" json:"expirestop,omitempty"`
	Wrapkit               *bool                                `protobuf:"varint,57,opt,name=wrapkit" json:"wrapkit,omitempty"`
	SkillwheelGem         *AppearanceFlagSkillWheelGem         `protobuf:"bytes,58,opt,name=skillwheel_gem,json=skillwheelGem" json:"skillwheel_gem,omitempty"`
	DualWielding          *bool                                `protobuf:"varint,59,opt,name=dual_wielding,json=dualWielding" json:"dual_wielding,omitempty"`
	Proficiency           *AppearanceFlagProficiency           `protobuf:"bytes,61,opt,name=proficiency" json:"proficiency,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AppearanceFlags) Reset() {
	*x = AppearanceFlags{}
	mi := &file_appearances_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlags) ProtoMessage() {}

func (x *AppearanceFlags) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlags.ProtoReflect.Descriptor instead.
func (*AppearanceFlags) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{8}
}

func (x *AppearanceFlags) GetBank() *AppearanceFlagBank {
	if x != nil {
		return x.Bank
	}
	return nil
}

func (x *AppearanceFlags) GetClip() bool {
	if x != nil && x.Clip != nil {
		return *x.Clip
	}
	return false
}

func (x *AppearanceFlags) GetBottom() bool {
	if x != nil && x.Bottom != nil {
		return *x.Bottom
	}
	return false
}

func (x *AppearanceFlags) GetTop() bool {
	if x != nil && x.Top != nil {
		return *x.Top
	}
	return false
}

func (x *AppearanceFlags) GetContainer() bool {
	if x != nil && x.Container != nil {
		return *x.Container
	}
	return false
}

func (x *AppearanceFlags) GetCumulative() bool {
	if x != nil && x.Cumulative != nil {
		return *x.Cumulative
	}
	return false
}

func (x *AppearanceFlags) GetUsable() bool {
	if x != nil && x.Usable != nil {
		return *x.Usable
	}
	return false
}

func (x *AppearanceFlags) GetForceuse() bool {
	if x != nil && x.Forceuse != nil {
		return *x.Forceuse
	}
	return false
}

func (x *AppearanceFlags) GetMultiuse() bool {
	if x != nil && x.Multiuse != nil {
		return *x.Multiuse
	}
	return false
}

func (x *AppearanceFlags) GetWrite() *AppearanceFlagWrite {
	if x != nil {
		return x.Write
	}
	return nil
}

func (x *AppearanceFlags) GetWriteOnce() *AppearanceFlagWriteOnce {
	if x != nil {
		return x.WriteOnce
	}
	return nil
}

func (x *AppearanceFlags) GetLiquidpool() bool {
	if x != nil && x.Liquidpool != nil {
		return *x.Liquidpool
	}
	return false
}

func (x *AppearanceFlags) GetUnpass() bool {
	if x != nil && x.Unpass != nil {
		return *x.Unpass
	}
	return false
}

func (x *AppearanceFlags) GetUnmove() bool {
	if x != nil && x.Unmove != nil {
		return *x.Unmove
	}
	return false
}

func (x *AppearanceFlags) GetUnsight() bool {
	if x != nil && x.Unsight != nil {
		return *x.Unsight
	}
	return false
}

func (x *AppearanceFlags) GetAvoid() bool {
	if x != nil && x.Avoid != nil {
		return *x.Avoid
	}
	return false
}

func (x *AppearanceFlags) GetNoMovementAnimation() bool {
	if x != nil && x.NoMovementAnimation != nil {
		return *x.NoMovementAnimation
	}
	return false
}

func (x *AppearanceFlags) GetTake() bool {
	if x != nil && x.Take != nil {
		return *x.Take
	}
	return false
}

func (x *AppearanceFlags) GetLiquidcontainer() bool {
	if x != nil && x.Liquidcontainer != nil {
		return *x.Liquidcontainer
	}
	return false
}

func (x *AppearanceFlags) GetHang() bool {
	if x != nil && x.Hang != nil {
		return *x.Hang
	}
	return false
}

func (x *AppearanceFlags) GetHook() *AppearanceFlagHook {
	if x != nil {
		return x.Hook
	}
	return nil
}

func (x *AppearanceFlags) GetRotate() bool {
	if x != nil && x.Rotate != nil {
		return *x.Rotate
	}
	return false
}

func (x *AppearanceFlags) GetLight() *AppearanceFlagLight {
	if x != nil {
		return x.Light
	}
	return nil
}

func (x *AppearanceFlags) GetDontHide() bool {
	if x != nil && x.DontHide != nil {
		return *x.DontHide
	}
	return false
}

func (x *AppearanceFlags) GetTranslucent() bool {
	if x != nil && x.Translucent != nil {
		return *x.Translucent
	}
	return false
}

func (x *AppearanceFlags) GetShift() *AppearanceFlagShift {
	if x != nil {
		return x.Shift
	}
	return nil
}

func (x *AppearanceFlags) GetHeight() *AppearanceFlagHeight {
	if x != nil {
		return x.Height
	}
	return nil
}

func (x *AppearanceFlags) GetLyingObject() bool {
	if x != nil && x.LyingObject != nil {
		return *x.LyingObject
	}
	return false
}

func (x *AppearanceFlags) GetAnimateAlways() bool {
	if x != nil && x.AnimateAlways != nil {
		return *x.AnimateAlways
	}
	return false
}

func (x *AppearanceFlags) GetAutomap() *AppearanceFlagAutomap {
	if x != nil {
		return x.Automap
	}
	return nil
}

func (x *AppearanceFlags) GetLenshelp() *AppearanceFlagLenshelp {
	if x != nil {
		return x.Lenshelp
	}
	return nil
}

func (x *AppearanceFlags) GetFullbank() bool {
	if x != nil && x.Fullbank != nil {
		return *x.Fullbank
	}
	return false
}

func (x *AppearanceFlags) GetIgnoreLook() bool {
	if x != nil && x.IgnoreLook != nil {
		return *x.IgnoreLook
	}
	return false
}

func (x *AppearanceFlags) GetClothes() *AppearanceFlagClothes {
	if x != nil {
		return x.Clothes
	}
	return nil
}

func (x *AppearanceFlags) GetDefaultAction() *AppearanceFlagDefaultAction {
	if x != nil {
		return x.DefaultAction
	}
	return nil
}

func (x *AppearanceFlags) GetMarket() *AppearanceFlagMarket {
	if x != nil {
		return x.Market
	}
	return nil
}

func (x *AppearanceFlags) GetWrap() bool {
	if x != nil && x.Wrap != nil {
		return *x.Wrap
	}
	return false
}

func (x *AppearanceFlags) GetUnwrap() bool {
	if x != nil && x.Unwrap != nil {
		return *x.Unwrap
	}
	return false
}

func (x *AppearanceFlags) GetTopeffect() bool {
	if x != nil && x.Topeffect != nil {
		return *x.Topeffect
	}
	return false
}

func (x *AppearanceFlags) GetNpcsaledata() []*AppearanceFlagNPC {
	if x != nil {
		return x.Npcsaledata
	}
	return nil
}

func (x *AppearanceFlags) GetChangedtoexpire() *AppearanceFlagChangedToExpire {
	if x != nil {
		return x.Changedtoexpire
	}
	return nil
}

func (x *AppearanceFlags) GetCorpse() bool {
	if x != nil && x.Corpse != nil {
		return *x.Corpse
	}
	return false
}

func (x *AppearanceFlags) GetPlayerCorpse() bool {
	if x != nil && x.PlayerCorpse != nil {
		return *x.PlayerCorpse
	}
	return false
}

func (x *AppearanceFlags) GetCyclopediaitem() *AppearanceFlagCyclopedia {
	if x != nil {
		return x.Cyclopediaitem
	}
	return nil
}

func (x *AppearanceFlags) GetAmmo() bool {
	if x != nil && x.Ammo != nil {
		return *x.Ammo
	}
	return false
}

func (x *AppearanceFlags) GetShowOffSocket() bool {
	if x != nil && x.ShowOffSocket != nil {
		return *x.ShowOffSocket
	}
	return false
}

func (x *AppearanceFlags) GetReportable() bool {
	if x != nil && x.Reportable != nil {
		return *x.Reportable
	}
	return false
}

func (x *AppearanceFlags) GetUpgradeclassification() *AppearanceFlagUpgradeClassification {
	if x != nil {
		return x.Upgradeclassification
	}
	return nil
}

func (x *AppearanceFlags) GetReverseAddonsEast() bool {
	if x != nil && x.ReverseAddonsEast != nil {
		return *x.ReverseAddonsEast
	}
	return false
}

func (x *AppearanceFlags) GetReverseAddonsWest() bool {
	if x != nil && x.ReverseAddonsWest != nil {
		return *x.ReverseAddonsWest
	}
	return false
}

func (x *AppearanceFlags) GetReverseAddonsSouth() bool {
	if x != nil && x.ReverseAddonsSouth != nil {
		return *x.ReverseAddonsSouth
	}
	return false
}

func (x *AppearanceFlags) GetReverseAddonsNorth() bool {
	if x != nil && x.ReverseAddonsNorth != nil {
		return *x.ReverseAddonsNorth
	}
	return false
}

func (x *AppearanceFlags) GetWearout() bool {
	if x != nil && x.Wearout != nil {
		return *x.Wearout
	}
	return false
}

func (x *AppearanceFlags) GetClockexpire() bool {
	if x != nil && x.Clockexpire != nil {
		return *x.Clockexpire
	}
	return false
}

func (x *AppearanceFlags) GetExpire() bool {
	if x != nil && x.Expire != nil {
		return *x.Expire
	}
	return false
}

func (x *AppearanceFlags) GetExpirestop() bool {
	if x != nil && x.Expirestop != nil {
		return *x.Expirestop
	}
	return false
}

func (x *AppearanceFlags) GetWrapkit() bool {
	if x != nil && x.Wrapkit != nil {
		return *x.Wrapkit
	}
	return false
}

func (x *AppearanceFlags) GetSkillwheelGem() *AppearanceFlagSkillWheelGem {
	if x != nil {
		return x.SkillwheelGem
	}
	return nil
}

func (x *AppearanceFlags) GetDualWielding() bool {
	if x != nil && x.DualWielding != nil {
		return *x.DualWielding
	}
	return false
}

func (x *AppearanceFlags) GetProficiency() *AppearanceFlagProficiency {
	if x != nil {
		return x.Proficiency
	}
	return nil
}

type AppearanceFlagUpgradeClassification struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UpgradeClassification *uint32                `protobuf:"varint,1,opt,name=upgrade_classification,json=upgradeClassification" json:"upgrade_classification,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AppearanceFlagUpgradeClassification) Reset() {
	*x = AppearanceFlagUpgradeClassification{}
	mi := &file_appearances_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagUpgradeClassification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagUpgradeClassification) ProtoMessage() {}

func (x *AppearanceFlagUpgradeClassification) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagUpgradeClassification.ProtoReflect.Descriptor instead.
func (*AppearanceFlagUpgradeClassification) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{9}
}

func (x *AppearanceFlagUpgradeClassification) GetUpgradeClassification() uint32 {
	if x != nil && x.UpgradeClassification != nil {
		return *x.UpgradeClassification
	}
	return 0
}

type AppearanceFlagBank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Waypoints     *uint32                `protobuf:"varint,1,opt,name=waypoints" json:"waypoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppearanceFlagBank) Reset() {
	*x = AppearanceFlagBank{}
	mi := &file_appearances_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagBank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagBank) ProtoMessage() {}

func (x *AppearanceFlagBank) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagBank.ProtoReflect.Descriptor instead.
func (*AppearanceFlagBank) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{10}
}

func (x *AppearanceFlagBank) GetWaypoints() uint32 {
	if x != nil && x.Waypoints != nil {
		return *x.Waypoints
	}
	return 0
}

type AppearanceFlagWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxTextLength *uint32                `protobuf:"varint,1,opt,name=max_text_length,json=maxTextLength" json:"max_text_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppearanceFlagWrite) Reset() {
	*x = AppearanceFlagWrite{}
	mi := &file_appearances_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagWrite) ProtoMessage() {}

func (x *AppearanceFlagWrite) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagWrite.ProtoReflect.Descriptor instead.
func (*AppearanceFlagWrite) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{11}
}

func (x *AppearanceFlagWrite) GetMaxTextLength() uint32 {
	if x != nil && x.MaxTextLength != nil {
		return *x.MaxTextLength
	}
	return 0
}

type AppearanceFlagWriteOnce struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxTextLengthOnce *uint32                `protobuf:"varint,1,opt,name=max_text_length_once,json=maxTextLengthOnce" json:"max_text_length_once,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppearanceFlagWriteOnce) Reset() {
	*x = AppearanceFlagWriteOnce{}
	mi := &file_appearances_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagWriteOnce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagWriteOnce) ProtoMessage() {}

func (x *AppearanceFlagWriteOnce) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagWriteOnce.ProtoReflect.Descriptor instead.
func (*AppearanceFlagWriteOnce) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{12}
}

func (x *AppearanceFlagWriteOnce) GetMaxTextLengthOnce() uint32 {
	if x != nil && x.MaxTextLengthOnce != nil {
		return *x.MaxTextLengthOnce
	}
	return 0
}

type AppearanceFlagLight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brightness    *uint32                `protobuf:"varint,1,opt,name=brightness" json:"brightness,omitempty"`
	Color         *uint32                `protobuf:"varint,2,opt,name=color" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppearanceFlagLight) Reset() {
	*x = AppearanceFlagLight{}
	mi := &file_appearances_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagLight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagLight) ProtoMessage() {}

func (x *AppearanceFlagLight) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagLight.ProtoReflect.Descriptor instead.
func (*AppearanceFlagLight) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{13}
}

func (x *AppearanceFlagLight) GetBrightness() uint32 {
	if x != nil && x.Brightness != nil {
		return *x.Brightness
	}
	return 0
}

func (x *AppearanceFlagLight) GetColor() uint32 {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return 0
}

type AppearanceFlagHeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elevation     *uint32                `protobuf:"varint,1,opt,name=elevation" json:"elevation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppearanceFlagHeight) Reset() {
	*x = AppearanceFlagHeight{}
	mi := &file_appearances_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagHeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagHeight) ProtoMessage() {}

func (x *AppearanceFlagHeight) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagHeight.ProtoReflect.Descriptor instead.
func (*AppearanceFlagHeight) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{14}
}

func (x *AppearanceFlagHeight) GetElevation() uint32 {
	if x != nil && x.Elevation != nil {
		return *x.Elevation
	}
	return 0
}

type AppearanceFlagShift struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *uint32                `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y             *uint32                `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppearanceFlagShift) Reset() {
	*x = AppearanceFlagShift{}
	mi := &file_appearances_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagShift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagShift) ProtoMessage() {}

func (x *AppearanceFlagShift) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagShift.ProtoReflect.Descriptor instead.
func (*AppearanceFlagShift) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{15}
}

func (x *AppearanceFlagShift) GetX() uint32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *AppearanceFlagShift) GetY() uint32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type AppearanceFlagClothes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          *uint32                `protobuf:"varint,1,opt,name=slot" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppearanceFlagClothes) Reset() {
	*x = AppearanceFlagClothes{}
	mi := &file_appearances_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagClothes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagClothes) ProtoMessage() {}

func (x *AppearanceFlagClothes) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagClothes.ProtoReflect.Descriptor instead.
func (*AppearanceFlagClothes) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{16}
}

func (x *AppearanceFlagClothes) GetSlot() uint32 {
	if x != nil && x.Slot != nil {
		return *x.Slot
	}
	return 0
}

type AppearanceFlagDefaultAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *PLAYER_ACTION         `protobuf:"varint,1,opt,name=action,enum=Canary.protobuf.appearances.PLAYER_ACTION" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppearanceFlagDefaultAction) Reset() {
	*x = AppearanceFlagDefaultAction{}
	mi := &file_appearances_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagDefaultAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagDefaultAction) ProtoMessage() {}

func (x *AppearanceFlagDefaultAction) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagDefaultAction.ProtoReflect.Descriptor instead.
func (*AppearanceFlagDefaultAction) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{17}
}

func (x *AppearanceFlagDefaultAction) GetAction() PLAYER_ACTION {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return PLAYER_ACTION_PLAYER_ACTION_NONE
}

type AppearanceFlagMarket struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Category             *ITEM_CATEGORY         `protobuf:"varint,1,opt,name=category,enum=Canary.protobuf.appearances.ITEM_CATEGORY" json:"category,omitempty"`
	TradeAsObjectId      *uint32                `protobuf:"varint,2,opt,name=trade_as_object_id,json=tradeAsObjectId" json:"trade_as_object_id,omitempty"`
	ShowAsObjectId       *uint32                `protobuf:"varint,3,opt,name=show_as_object_id,json=showAsObjectId" json:"show_as_object_id,omitempty"`
	RestrictToProfession []PLAYER_PROFESSION    `protobuf:"varint,5,rep,name=restrict_to_profession,json=restrictToProfession,enum=Canary.protobuf.appearances.PLAYER_PROFESSION" json:"restrict_to_profession,omitempty"`
	MinimumLevel         *uint32                `protobuf:"varint,6,opt,name=minimum_level,json=minimumLevel" json:"minimum_level,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AppearanceFlagMarket) Reset() {
	*x = AppearanceFlagMarket{}
	mi := &file_appearances_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagMarket) ProtoMessage() {}

func (x *AppearanceFlagMarket) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagMarket.ProtoReflect.Descriptor instead.
func (*AppearanceFlagMarket) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{18}
}

func (x *AppearanceFlagMarket) GetCategory() ITEM_CATEGORY {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ITEM_CATEGORY_ITEM_CATEGORY_ARMORS
}

func (x *AppearanceFlagMarket) GetTradeAsObjectId() uint32 {
	if x != nil && x.TradeAsObjectId != nil {
		return *x.TradeAsObjectId
	}
	return 0
}

func (x *AppearanceFlagMarket) GetShowAsObjectId() uint32 {
	if x != nil && x.ShowAsObjectId != nil {
		return *x.ShowAsObjectId
	}
	return 0
}

func (x *AppearanceFlagMarket) GetRestrictToProfession() []PLAYER_PROFESSION {
	if x != nil {
		return x.RestrictToProfession
	}
	return nil
}

func (x *AppearanceFlagMarket) GetMinimumLevel() uint32 {
	if x != nil && x.MinimumLevel != nil {
		return *x.MinimumLevel
	}
	return 0
}

type AppearanceFlagNPC struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Name                         []byte                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Location                     []byte                 `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	SalePrice                    *uint32                `protobuf:"varint,3,opt,name=sale_price,json=salePrice" json:"sale_price,omitempty"`
	BuyPrice                     *uint32                `protobuf:"varint,4,opt,name=buy_price,json=buyPrice" json:"buy_price,omitempty"`
	CurrencyObjectTypeId         *uint32                `protobuf:"varint,5,opt,name=currency_object_type_id,json=currencyObjectTypeId" json:"currency_object_type_id,omitempty"`
	CurrencyQuestFlagDisplayName []byte                 `protobuf:"bytes,6,opt,name=currency_quest_flag_display_name,json=currencyQuestFlagDisplayName" json:"currency_quest_flag_display_name,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *AppearanceFlagNPC) Reset() {
	*x = AppearanceFlagNPC{}
	mi := &file_appearances_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagNPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagNPC) ProtoMessage() {}

func (x *AppearanceFlagNPC) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagNPC.ProtoReflect.Descriptor instead.
func (*AppearanceFlagNPC) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{19}
}

func (x *AppearanceFlagNPC) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *AppearanceFlagNPC) GetLocation() []byte {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *AppearanceFlagNPC) GetSalePrice() uint32 {
	if x != nil && x.SalePrice != nil {
		return *x.SalePrice
	}
	return 0
}

func (x *AppearanceFlagNPC) GetBuyPrice() uint32 {
	if x != nil && x.BuyPrice != nil {
		return *x.BuyPrice
	}
	return 0
}

func (x *AppearanceFlagNPC) GetCurrencyObjectTypeId() uint32 {
	if x != nil && x.CurrencyObjectTypeId != nil {
		return *x.CurrencyObjectTypeId
	}
	return 0
}

func (x *AppearanceFlagNPC) GetCurrencyQuestFlagDisplayName() []byte {
	if x != nil {
		return x.CurrencyQuestFlagDisplayName
	}
	return nil
}

type AppearanceFlagAutomap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         *uint32                `protobuf:"varint,1,opt,name=color" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppearanceFlagAutomap) Reset() {
	*x = AppearanceFlagAutomap{}
	mi := &file_appearances_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagAutomap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagAutomap) ProtoMessage() {}

func (x *AppearanceFlagAutomap) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagAutomap.ProtoReflect.Descriptor instead.
func (*AppearanceFlagAutomap) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{20}
}

func (x *AppearanceFlagAutomap) GetColor() uint32 {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return 0
}

type AppearanceFlagHook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     *HOOK_TYPE             `protobuf:"varint,1,opt,name=direction,enum=Canary.protobuf.appearances.HOOK_TYPE" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppearanceFlagHook) Reset() {
	*x = AppearanceFlagHook{}
	mi := &file_appearances_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagHook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagHook) ProtoMessage() {}

func (x *AppearanceFlagHook) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagHook.ProtoReflect.Descriptor instead.
func (*AppearanceFlagHook) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{21}
}

func (x *AppearanceFlagHook) GetDirection() HOOK_TYPE {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return HOOK_TYPE_HOOK_TYPE_SOUTH
}

type AppearanceFlagLenshelp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppearanceFlagLenshelp) Reset() {
	*x = AppearanceFlagLenshelp{}
	mi := &file_appearances_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagLenshelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagLenshelp) ProtoMessage() {}

func (x *AppearanceFlagLenshelp) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagLenshelp.ProtoReflect.Descriptor instead.
func (*AppearanceFlagLenshelp) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{22}
}

func (x *AppearanceFlagLenshelp) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type AppearanceFlagChangedToExpire struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FormerObjectTypeid *uint32                `protobuf:"varint,1,opt,name=former_object_typeid,json=formerObjectTypeid" json:"former_object_typeid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AppearanceFlagChangedToExpire) Reset() {
	*x = AppearanceFlagChangedToExpire{}
	mi := &file_appearances_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagChangedToExpire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagChangedToExpire) ProtoMessage() {}

func (x *AppearanceFlagChangedToExpire) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagChangedToExpire.ProtoReflect.Descriptor instead.
func (*AppearanceFlagChangedToExpire) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{23}
}

func (x *AppearanceFlagChangedToExpire) GetFormerObjectTypeid() uint32 {
	if x != nil && x.FormerObjectTypeid != nil {
		return *x.FormerObjectTypeid
	}
	return 0
}

type AppearanceFlagCyclopedia struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CyclopediaType *uint32                `protobuf:"varint,1,opt,name=cyclopedia_type,json=cyclopediaType" json:"cyclopedia_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppearanceFlagCyclopedia) Reset() {
	*x = AppearanceFlagCyclopedia{}
	mi := &file_appearances_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagCyclopedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagCyclopedia) ProtoMessage() {}

func (x *AppearanceFlagCyclopedia) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagCyclopedia.ProtoReflect.Descriptor instead.
func (*AppearanceFlagCyclopedia) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{24}
}

func (x *AppearanceFlagCyclopedia) GetCyclopediaType() uint32 {
	if x != nil && x.CyclopediaType != nil {
		return *x.CyclopediaType
	}
	return 0
}

type AppearanceFlagSkillWheelGem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GemQualityId  *uint32                `protobuf:"varint,1,opt,name=gem_quality_id,json=gemQualityId" json:"gem_quality_id,omitempty"`
	VocationId    *uint32                `protobuf:"varint,2,opt,name=vocation_id,json=vocationId" json:"vocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppearanceFlagSkillWheelGem) Reset() {
	*x = AppearanceFlagSkillWheelGem{}
	mi := &file_appearances_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagSkillWheelGem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagSkillWheelGem) ProtoMessage() {}

func (x *AppearanceFlagSkillWheelGem) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagSkillWheelGem.ProtoReflect.Descriptor instead.
func (*AppearanceFlagSkillWheelGem) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{25}
}

func (x *AppearanceFlagSkillWheelGem) GetGemQualityId() uint32 {
	if x != nil && x.GemQualityId != nil {
		return *x.GemQualityId
	}
	return 0
}

func (x *AppearanceFlagSkillWheelGem) GetVocationId() uint32 {
	if x != nil && x.VocationId != nil {
		return *x.VocationId
	}
	return 0
}

type AppearanceFlagProficiency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProficiencyId *uint32                `protobuf:"varint,1,opt,name=proficiency_id,json=proficiencyId" json:"proficiency_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppearanceFlagProficiency) Reset() {
	*x = AppearanceFlagProficiency{}
	mi := &file_appearances_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppearanceFlagProficiency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppearanceFlagProficiency) ProtoMessage() {}

func (x *AppearanceFlagProficiency) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppearanceFlagProficiency.ProtoReflect.Descriptor instead.
func (*AppearanceFlagProficiency) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{26}
}

func (x *AppearanceFlagProficiency) GetProficiencyId() uint32 {
	if x != nil && x.ProficiencyId != nil {
		return *x.ProficiencyId
	}
	return 0
}

type SpecialMeaningAppearanceIds struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GoldCoinId      *uint32                `protobuf:"varint,1,opt,name=gold_coin_id,json=goldCoinId" json:"gold_coin_id,omitempty"`
	PlatinumCoinId  *uint32                `protobuf:"varint,2,opt,name=platinum_coin_id,json=platinumCoinId" json:"platinum_coin_id,omitempty"`
	CrystalCoinId   *uint32                `protobuf:"varint,3,opt,name=crystal_coin_id,json=crystalCoinId" json:"crystal_coin_id,omitempty"`
	TibiaCoinId     *uint32                `protobuf:"varint,4,opt,name=tibia_coin_id,json=tibiaCoinId" json:"tibia_coin_id,omitempty"`
	StampedLetterId *uint32                `protobuf:"varint,5,opt,name=stamped_letter_id,json=stampedLetterId" json:"stamped_letter_id,omitempty"`
	SupplyStashId   *uint32                `protobuf:"varint,6,opt,name=supply_stash_id,json=supplyStashId" json:"supply_stash_id,omitempty"`
	RewardChestId   *uint32                `protobuf:"varint,7,opt,name=reward_chest_id,json=rewardChestId" json:"reward_chest_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SpecialMeaningAppearanceIds) Reset() {
	*x = SpecialMeaningAppearanceIds{}
	mi := &file_appearances_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialMeaningAppearanceIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialMeaningAppearanceIds) ProtoMessage() {}

func (x *SpecialMeaningAppearanceIds) ProtoReflect() protoreflect.Message {
	mi := &file_appearances_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialMeaningAppearanceIds.ProtoReflect.Descriptor instead.
func (*SpecialMeaningAppearanceIds) Descriptor() ([]byte, []int) {
	return file_appearances_proto_rawDescGZIP(), []int{27}
}

func (x *SpecialMeaningAppearanceIds) GetGoldCoinId() uint32 {
	if x != nil && x.GoldCoinId != nil {
		return *x.GoldCoinId
	}
	return 0
}

func (x *SpecialMeaningAppearanceIds) GetPlatinumCoinId() uint32 {
	if x != nil && x.PlatinumCoinId != nil {
		return *x.PlatinumCoinId
	}
	return 0
}

func (x *SpecialMeaningAppearanceIds) GetCrystalCoinId() uint32 {
	if x != nil && x.CrystalCoinId != nil {
		return *x.CrystalCoinId
	}
	return 0
}

func (x *SpecialMeaningAppearanceIds) GetTibiaCoinId() uint32 {
	if x != nil && x.TibiaCoinId != nil {
		return *x.TibiaCoinId
	}
	return 0
}

func (x *SpecialMeaningAppearanceIds) GetStampedLetterId() uint32 {
	if x != nil && x.StampedLetterId != nil {
		return *x.StampedLetterId
	}
	return 0
}

func (x *SpecialMeaningAppearanceIds) GetSupplyStashId() uint32 {
	if x != nil && x.SupplyStashId != nil {
		return *x.SupplyStashId
	}
	return 0
}

func (x *SpecialMeaningAppearanceIds) GetRewardChestId() uint32 {
	if x != nil && x.RewardChestId != nil {
		return *x.RewardChestId
	}
	return 0
}

var File_appearances_proto protoreflect.FileDescriptor

const file_appearances_proto_rawDesc = "" +
	"\n" +
	"\x11appearances.proto\x12\x1bCanary.protobuf.appearances\"6\n" +
	"\n" +
	"Coordinate\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\rR\x01z\"\x92\x03\n" +
	"\vAppearances\x12?\n" +
	"\x06object\x18\x01 \x03(\v2'.Canary.protobuf.appearances.AppearanceR\x06object\x12?\n" +
	"\x06outfit\x18\x02 \x03(\v2'.Canary.protobuf.appearances.AppearanceR\x06outfit\x12?\n" +
	"\x06effect\x18\x03 \x03(\v2'.Canary.protobuf.appearances.AppearanceR\x06effect\x12A\n" +
	"\amissile\x18\x04 \x03(\v2'.Canary.protobuf.appearances.AppearanceR\amissile\x12}\n" +
	"\x1especial_meaning_appearance_ids\x18\x05 \x01(\v28.Canary.protobuf.appearances.SpecialMeaningAppearanceIdsR\x1bspecialMeaningAppearanceIds\"S\n" +
	"\vSpritePhase\x12!\n" +
	"\fduration_min\x18\x01 \x01(\rR\vdurationMin\x12!\n" +
	"\fduration_max\x18\x02 \x01(\rR\vdurationMax\"\xce\x02\n" +
	"\x0fSpriteAnimation\x12.\n" +
	"\x13default_start_phase\x18\x01 \x01(\rR\x11defaultStartPhase\x12\"\n" +
	"\fsynchronized\x18\x02 \x01(\bR\fsynchronized\x12,\n" +
	"\x12random_start_phase\x18\x03 \x01(\bR\x10randomStartPhase\x12M\n" +
	"\tloop_type\x18\x04 \x01(\x0e20.Canary.protobuf.appearances.ANIMATION_LOOP_TYPER\bloopType\x12\x1d\n" +
	"\n" +
	"loop_count\x18\x05 \x01(\rR\tloopCount\x12K\n" +
	"\fsprite_phase\x18\x06 \x03(\v2(.Canary.protobuf.appearances.SpritePhaseR\vspritePhase\"O\n" +
	"\x03Box\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\"\xa3\x03\n" +
	"\n" +
	"SpriteInfo\x12#\n" +
	"\rpattern_width\x18\x01 \x01(\rR\fpatternWidth\x12%\n" +
	"\x0epattern_height\x18\x02 \x01(\rR\rpatternHeight\x12#\n" +
	"\rpattern_depth\x18\x03 \x01(\rR\fpatternDepth\x12\x16\n" +
	"\x06layers\x18\x04 \x01(\rR\x06layers\x12\x1b\n" +
	"\tsprite_id\x18\x05 \x03(\rR\bspriteId\x12'\n" +
	"\x0fbounding_square\x18\a \x01(\rR\x0eboundingSquare\x12J\n" +
	"\tanimation\x18\x06 \x01(\v2,.Canary.protobuf.appearances.SpriteAnimationR\tanimation\x12\x1b\n" +
	"\tis_opaque\x18\b \x01(\bR\bisOpaque\x12]\n" +
	"\x1abounding_box_per_direction\x18\t \x03(\v2 .Canary.protobuf.appearances.BoxR\x17boundingBoxPerDirection\"\xc2\x01\n" +
	"\n" +
	"FrameGroup\x12Z\n" +
	"\x11fixed_frame_group\x18\x01 \x01(\x0e2..Canary.protobuf.appearances.FIXED_FRAME_GROUPR\x0ffixedFrameGroup\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12H\n" +
	"\vsprite_info\x18\x03 \x01(\v2'.Canary.protobuf.appearances.SpriteInfoR\n" +
	"spriteInfo\"\xe0\x01\n" +
	"\n" +
	"Appearance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12H\n" +
	"\vframe_group\x18\x02 \x03(\v2'.Canary.protobuf.appearances.FrameGroupR\n" +
	"frameGroup\x12B\n" +
	"\x05flags\x18\x03 \x01(\v2,.Canary.protobuf.appearances.AppearanceFlagsR\x05flags\x12\x12\n" +
	"\x04name\x18\x04 \x01(\fR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\fR\vdescription\"\x80\x16\n" +
	"\x0fAppearanceFlags\x12C\n" +
	"\x04bank\x18\x01 \x01(\v2/.Canary.protobuf.appearances.AppearanceFlagBankR\x04bank\x12\x12\n" +
	"\x04clip\x18\x02 \x01(\bR\x04clip\x12\x16\n" +
	"\x06bottom\x18\x03 \x01(\bR\x06bottom\x12\x10\n" +
	"\x03top\x18\x04 \x01(\bR\x03top\x12\x1c\n" +
	"\tcontainer\x18\x05 \x01(\bR\tcontainer\x12\x1e\n" +
	"\n" +
	"cumulative\x18\x06 \x01(\bR\n" +
	"cumulative\x12\x16\n" +
	"\x06usable\x18\a \x01(\bR\x06usable\x12\x1a\n" +
	"\bforceuse\x18\b \x01(\bR\bforceuse\x12\x1a\n" +
	"\bmultiuse\x18\t \x01(\bR\bmultiuse\x12F\n" +
	"\x05write\x18\n" +
	" \x01(\v20.Canary.protobuf.appearances.AppearanceFlagWriteR\x05write\x12S\n" +
	"\n" +
	"write_once\x18\v \x01(\v24.Canary.protobuf.appearances.AppearanceFlagWriteOnceR\twriteOnce\x12\x1e\n" +
	"\n" +
	"liquidpool\x18\f \x01(\bR\n" +
	"liquidpool\x12\x16\n" +
	"\x06unpass\x18\r \x01(\bR\x06unpass\x12\x16\n" +
	"\x06unmove\x18\x0e \x01(\bR\x06unmove\x12\x18\n" +
	"\aunsight\x18\x0f \x01(\bR\aunsight\x12\x14\n" +
	"\x05avoid\x18\x10 \x01(\bR\x05avoid\x122\n" +
	"\x15no_movement_animation\x18\x11 \x01(\bR\x13noMovementAnimation\x12\x12\n" +
	"\x04take\x18\x12 \x01(\bR\x04take\x12(\n" +
	"\x0fliquidcontainer\x18\x13 \x01(\bR\x0fliquidcontainer\x12\x12\n" +
	"\x04hang\x18\x14 \x01(\bR\x04hang\x12C\n" +
	"\x04hook\x18\x15 \x01(\v2/.Canary.protobuf.appearances.AppearanceFlagHookR\x04hook\x12\x16\n" +
	"\x06rotate\x18\x16 \x01(\bR\x06rotate\x12F\n" +
	"\x05light\x18\x17 \x01(\v20.Canary.protobuf.appearances.AppearanceFlagLightR\x05light\x12\x1b\n" +
	"\tdont_hide\x18\x18 \x01(\bR\bdontHide\x12 \n" +
	"\vtranslucent\x18\x19 \x01(\bR\vtranslucent\x12F\n" +
	"\x05shift\x18\x1a \x01(\v20.Canary.protobuf.appearances.AppearanceFlagShiftR\x05shift\x12I\n" +
	"\x06height\x18\x1b \x01(\v21.Canary.protobuf.appearances.AppearanceFlagHeightR\x06height\x12!\n" +
	"\flying_object\x18\x1c \x01(\bR\vlyingObject\x12%\n" +
	"\x0eanimate_always\x18\x1d \x01(\bR\ranimateAlways\x12L\n" +
	"\aautomap\x18\x1e \x01(\v22.Canary.protobuf.appearances.AppearanceFlagAutomapR\aautomap\x12O\n" +
	"\blenshelp\x18\x1f \x01(\v23.Canary.protobuf.appearances.AppearanceFlagLenshelpR\blenshelp\x12\x1a\n" +
	"\bfullbank\x18  \x01(\bR\bfullbank\x12\x1f\n" +
	"\vignore_look\x18! \x01(\bR\n" +
	"ignoreLook\x12L\n" +
	"\aclothes\x18\" \x01(\v22.Canary.protobuf.appearances.AppearanceFlagClothesR\aclothes\x12_\n" +
	"\x0edefault_action\x18# \x01(\v28.Canary.protobuf.appearances.AppearanceFlagDefaultActionR\rdefaultAction\x12I\n" +
	"\x06market\x18$ \x01(\v21.Canary.protobuf.appearances.AppearanceFlagMarketR\x06market\x12\x12\n" +
	"\x04wrap\x18% \x01(\bR\x04wrap\x12\x16\n" +
	"\x06unwrap\x18& \x01(\bR\x06unwrap\x12\x1c\n" +
	"\ttopeffect\x18' \x01(\bR\ttopeffect\x12P\n" +
	"\vnpcsaledata\x18( \x03(\v2..Canary.protobuf.appearances.AppearanceFlagNPCR\vnpcsaledata\x12d\n" +
	"\x0fchangedtoexpire\x18) \x01(\v2:.Canary.protobuf.appearances.AppearanceFlagChangedToExpireR\x0fchangedtoexpire\x12\x16\n" +
	"\x06corpse\x18* \x01(\bR\x06corpse\x12#\n" +
	"\rplayer_corpse\x18+ \x01(\bR\fplayerCorpse\x12]\n" +
	"\x0ecyclopediaitem\x18, \x01(\v25.Canary.protobuf.appearances.AppearanceFlagCyclopediaR\x0ecyclopediaitem\x12\x12\n" +
	"\x04ammo\x18- \x01(\bR\x04ammo\x12&\n" +
	"\x0fshow_off_socket\x18. \x01(\bR\rshowOffSocket\x12\x1e\n" +
	"\n" +
	"reportable\x18/ \x01(\bR\n" +
	"reportable\x12v\n" +
	"\x15upgradeclassification\x180 \x01(\v2@.Canary.protobuf.appearances.AppearanceFlagUpgradeClassificationR\x15upgradeclassification\x12.\n" +
	"\x13reverse_addons_east\x181 \x01(\bR\x11reverseAddonsEast\x12.\n" +
	"\x13reverse_addons_west\x182 \x01(\bR\x11reverseAddonsWest\x120\n" +
	"\x14reverse_addons_south\x183 \x01(\bR\x12reverseAddonsSouth\x120\n" +
	"\x14reverse_addons_north\x184 \x01(\bR\x12reverseAddonsNorth\x12\x18\n" +
	"\awearout\x185 \x01(\bR\awearout\x12 \n" +
	"\vclockexpire\x186 \x01(\bR\vclockexpire\x12\x16\n" +
	"\x06expire\x187 \x01(\bR\x06expire\x12\x1e\n" +
	"\n" +
	"expirestop\x188 \x01(\bR\n" +
	"expirestop\x12\x18\n" +
	"\awrapkit\x189 \x01(\bR\awrapkit\x12_\n" +
	"\x0eskillwheel_gem\x18: \x01(\v28.Canary.protobuf.appearances.AppearanceFlagSkillWheelGemR\rskillwheelGem\x12#\n" +
	"\rdual_wielding\x18; \x01(\bR\fdualWielding\x12X\n" +
	"\vproficiency\x18= \x01(\v26.Canary.protobuf.appearances.AppearanceFlagProficiencyR\vproficiency\"\\\n" +
	"#AppearanceFlagUpgradeClassification\x125\n" +
	"\x16upgrade_classification\x18\x01 \x01(\rR\x15upgradeClassification\"2\n" +
	"\x12AppearanceFlagBank\x12\x1c\n" +
	"\twaypoints\x18\x01 \x01(\rR\twaypoints\"=\n" +
	"\x13AppearanceFlagWrite\x12&\n" +
	"\x0fmax_text_length\x18\x01 \x01(\rR\rmaxTextLength\"J\n" +
	"\x17AppearanceFlagWriteOnce\x12/\n" +
	"\x14max_text_length_once\x18\x01 \x01(\rR\x11maxTextLengthOnce\"K\n" +
	"\x13AppearanceFlagLight\x12\x1e\n" +
	"\n" +
	"brightness\x18\x01 \x01(\rR\n" +
	"brightness\x12\x14\n" +
	"\x05color\x18\x02 \x01(\rR\x05color\"4\n" +
	"\x14AppearanceFlagHeight\x12\x1c\n" +
	"\televation\x18\x01 \x01(\rR\televation\"1\n" +
	"\x13AppearanceFlagShift\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01y\"+\n" +
	"\x15AppearanceFlagClothes\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\"a\n" +
	"\x1bAppearanceFlagDefaultAction\x12B\n" +
	"\x06action\x18\x01 \x01(\x0e2*.Canary.protobuf.appearances.PLAYER_ACTIONR\x06action\"\xc1\x02\n" +
	"\x14AppearanceFlagMarket\x12F\n" +
	"\bcategory\x18\x01 \x01(\x0e2*.Canary.protobuf.appearances.ITEM_CATEGORYR\bcategory\x12+\n" +
	"\x12trade_as_object_id\x18\x02 \x01(\rR\x0ftradeAsObjectId\x12)\n" +
	"\x11show_as_object_id\x18\x03 \x01(\rR\x0eshowAsObjectId\x12d\n" +
	"\x16restrict_to_profession\x18\x05 \x03(\x0e2..Canary.protobuf.appearances.PLAYER_PROFESSIONR\x14restrictToProfession\x12#\n" +
	"\rminimum_level\x18\x06 \x01(\rR\fminimumLevel\"\xfe\x01\n" +
	"\x11AppearanceFlagNPC\x12\x12\n" +
	"\x04name\x18\x01 \x01(\fR\x04name\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\fR\blocation\x12\x1d\n" +
	"\n" +
	"sale_price\x18\x03 \x01(\rR\tsalePrice\x12\x1b\n" +
	"\tbuy_price\x18\x04 \x01(\rR\bbuyPrice\x125\n" +
	"\x17currency_object_type_id\x18\x05 \x01(\rR\x14currencyObjectTypeId\x12F\n" +
	" currency_quest_flag_display_name\x18\x06 \x01(\fR\x1ccurrencyQuestFlagDisplayName\"-\n" +
	"\x15AppearanceFlagAutomap\x12\x14\n" +
	"\x05color\x18\x01 \x01(\rR\x05color\"Z\n" +
	"\x12AppearanceFlagHook\x12D\n" +
	"\tdirection\x18\x01 \x01(\x0e2&.Canary.protobuf.appearances.HOOK_TYPER\tdirection\"(\n" +
	"\x16AppearanceFlagLenshelp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"Q\n" +
	"\x1dAppearanceFlagChangedToExpire\x120\n" +
	"\x14former_object_typeid\x18\x01 \x01(\rR\x12formerObjectTypeid\"C\n" +
	"\x18AppearanceFlagCyclopedia\x12'\n" +
	"\x0fcyclopedia_type\x18\x01 \x01(\rR\x0ecyclopediaType\"d\n" +
	"\x1bAppearanceFlagSkillWheelGem\x12$\n" +
	"\x0egem_quality_id\x18\x01 \x01(\rR\fgemQualityId\x12\x1f\n" +
	"\vvocation_id\x18\x02 \x01(\rR\n" +
	"vocationId\"B\n" +
	"\x19AppearanceFlagProficiency\x12%\n" +
	"\x0eproficiency_id\x18\x01 \x01(\rR\rproficiencyId\"\xb1\x02\n" +
	"\x1bSpecialMeaningAppearanceIds\x12 \n" +
	"\fgold_coin_id\x18\x01 \x01(\rR\n" +
	"goldCoinId\x12(\n" +
	"\x10platinum_coin_id\x18\x02 \x01(\rR\x0eplatinumCoinId\x12&\n" +
	"\x0fcrystal_coin_id\x18\x03 \x01(\rR\rcrystalCoinId\x12\"\n" +
	"\rtibia_coin_id\x18\x04 \x01(\rR\vtibiaCoinId\x12*\n" +
	"\x11stamped_letter_id\x18\x05 \x01(\rR\x0fstampedLetterId\x12&\n" +
	"\x0fsupply_stash_id\x18\x06 \x01(\rR\rsupplyStashId\x12&\n" +
	"\x0freward_chest_id\x18\a \x01(\rR\rrewardChestId*\x94\x01\n" +
	"\rPLAYER_ACTION\x12\x16\n" +
	"\x12PLAYER_ACTION_NONE\x10\x00\x12\x16\n" +
	"\x12PLAYER_ACTION_LOOK\x10\x01\x12\x15\n" +
	"\x11PLAYER_ACTION_USE\x10\x02\x12\x16\n" +
	"\x12PLAYER_ACTION_OPEN\x10\x03\x12$\n" +
	" PLAYER_ACTION_AUTOWALK_HIGHLIGHT\x10\x04*\x81\a\n" +
	"\rITEM_CATEGORY\x12\x18\n" +
	"\x14ITEM_CATEGORY_ARMORS\x10\x01\x12\x19\n" +
	"\x15ITEM_CATEGORY_AMULETS\x10\x02\x12\x17\n" +
	"\x13ITEM_CATEGORY_BOOTS\x10\x03\x12\x1c\n" +
	"\x18ITEM_CATEGORY_CONTAINERS\x10\x04\x12\x1c\n" +
	"\x18ITEM_CATEGORY_DECORATION\x10\x05\x12\x16\n" +
	"\x12ITEM_CATEGORY_FOOD\x10\x06\x12\x1e\n" +
	"\x1aITEM_CATEGORY_HELMETS_HATS\x10\a\x12\x16\n" +
	"\x12ITEM_CATEGORY_LEGS\x10\b\x12\x18\n" +
	"\x14ITEM_CATEGORY_OTHERS\x10\t\x12\x19\n" +
	"\x15ITEM_CATEGORY_POTIONS\x10\n" +
	"\x12\x17\n" +
	"\x13ITEM_CATEGORY_RINGS\x10\v\x12\x17\n" +
	"\x13ITEM_CATEGORY_RUNES\x10\f\x12\x19\n" +
	"\x15ITEM_CATEGORY_SHIELDS\x10\r\x12\x17\n" +
	"\x13ITEM_CATEGORY_TOOLS\x10\x0e\x12\x1b\n" +
	"\x17ITEM_CATEGORY_VALUABLES\x10\x0f\x12\x1c\n" +
	"\x18ITEM_CATEGORY_AMMUNITION\x10\x10\x12\x16\n" +
	"\x12ITEM_CATEGORY_AXES\x10\x11\x12\x17\n" +
	"\x13ITEM_CATEGORY_CLUBS\x10\x12\x12\"\n" +
	"\x1eITEM_CATEGORY_DISTANCE_WEAPONS\x10\x13\x12\x18\n" +
	"\x14ITEM_CATEGORY_SWORDS\x10\x14\x12\x1c\n" +
	"\x18ITEM_CATEGORY_WANDS_RODS\x10\x15\x12!\n" +
	"\x1dITEM_CATEGORY_PREMIUM_SCROLLS\x10\x16\x12\x1d\n" +
	"\x19ITEM_CATEGORY_TIBIA_COINS\x10\x17\x12#\n" +
	"\x1fITEM_CATEGORY_CREATURE_PRODUCTS\x10\x18\x12\x18\n" +
	"\x14ITEM_CATEGORY_QUIVER\x10\x19\x12\x1f\n" +
	"\x1bITEM_CATEGORY_TWOHANDWEAPON\x10\x1a\x12\x1e\n" +
	"\x1aITEM_CATEGORY_FIST_WEAPONS\x10\x1b\x12\x1a\n" +
	"\x16ITEM_CATEGORY_BACKPACK\x10\x1c\x12\x1f\n" +
	"\x1bITEM_CATEGORY_ONEHANDWEAPON\x10\x1d\x12\x17\n" +
	"\x13ITEM_CATEGORY_ARROW\x10\x1e\x12\x1b\n" +
	"\x17ITEM_CATEGORY_SOULCORES\x10\x1f*\x89\x02\n" +
	"\x11PLAYER_PROFESSION\x12\"\n" +
	"\x15PLAYER_PROFESSION_ANY\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1a\n" +
	"\x16PLAYER_PROFESSION_NONE\x10\x00\x12\x1c\n" +
	"\x18PLAYER_PROFESSION_KNIGHT\x10\x01\x12\x1d\n" +
	"\x19PLAYER_PROFESSION_PALADIN\x10\x02\x12\x1e\n" +
	"\x1aPLAYER_PROFESSION_SORCERER\x10\x03\x12\x1b\n" +
	"\x17PLAYER_PROFESSION_DRUID\x10\x04\x12\x1a\n" +
	"\x16PLAYER_PROFESSION_MONK\x10\x05\x12\x1e\n" +
	"\x1aPLAYER_PROFESSION_PROMOTED\x10\n" +
	"*\x83\x01\n" +
	"\x13ANIMATION_LOOP_TYPE\x12)\n" +
	"\x1cANIMATION_LOOP_TYPE_PINGPONG\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12 \n" +
	"\x1cANIMATION_LOOP_TYPE_INFINITE\x10\x00\x12\x1f\n" +
	"\x1bANIMATION_LOOP_TYPE_COUNTED\x10\x01*4\n" +
	"\tHOOK_TYPE\x12\x13\n" +
	"\x0fHOOK_TYPE_SOUTH\x10\x01\x12\x12\n" +
	"\x0eHOOK_TYPE_EAST\x10\x02*\x81\x01\n" +
	"\x11FIXED_FRAME_GROUP\x12!\n" +
	"\x1dFIXED_FRAME_GROUP_OUTFIT_IDLE\x10\x00\x12#\n" +
	"\x1fFIXED_FRAME_GROUP_OUTFIT_MOVING\x10\x01\x12$\n" +
	" FIXED_FRAME_GROUP_OBJECT_INITIAL\x10\x02B\x02H\x03"

var (
	file_appearances_proto_rawDescOnce sync.Once
	file_appearances_proto_rawDescData []byte
)

func file_appearances_proto_rawDescGZIP() []byte {
	file_appearances_proto_rawDescOnce.Do(func() {
		file_appearances_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appearances_proto_rawDesc), len(file_appearances_proto_rawDesc)))
	})
	return file_appearances_proto_rawDescData
}

var file_appearances_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_appearances_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_appearances_proto_goTypes = []any{
	(PLAYER_ACTION)(0),                          // 0: Canary.protobuf.appearances.PLAYER_ACTION
	(ITEM_CATEGORY)(0),                          // 1: Canary.protobuf.appearances.ITEM_CATEGORY
	(PLAYER_PROFESSION)(0),                      // 2: Canary.protobuf.appearances.PLAYER_PROFESSION
	(ANIMATION_LOOP_TYPE)(0),                    // 3: Canary.protobuf.appearances.ANIMATION_LOOP_TYPE
	(HOOK_TYPE)(0),                              // 4: Canary.protobuf.appearances.HOOK_TYPE
	(FIXED_FRAME_GROUP)(0),                      // 5: Canary.protobuf.appearances.FIXED_FRAME_GROUP
	(*Coordinate)(nil),                          // 6: Canary.protobuf.appearances.Coordinate
	(*Appearances)(nil),                         // 7: Canary.protobuf.appearances.Appearances
	(*SpritePhase)(nil),                         // 8: Canary.protobuf.appearances.SpritePhase
	(*SpriteAnimation)(nil),                     // 9: Canary.protobuf.appearances.SpriteAnimation
	(*Box)(nil),                                 // 10: Canary.protobuf.appearances.Box
	(*SpriteInfo)(nil),                          // 11: Canary.protobuf.appearances.SpriteInfo
	(*FrameGroup)(nil),                          // 12: Canary.protobuf.appearances.FrameGroup
	(*Appearance)(nil),                          // 13: Canary.protobuf.appearances.Appearance
	(*AppearanceFlags)(nil),                     // 14: Canary.protobuf.appearances.AppearanceFlags
	(*AppearanceFlagUpgradeClassification)(nil), // 15: Canary.protobuf.appearances.AppearanceFlagUpgradeClassification
	(*AppearanceFlagBank)(nil),                  // 16: Canary.protobuf.appearances.AppearanceFlagBank
	(*AppearanceFlagWrite)(nil),                 // 17: Canary.protobuf.appearances.AppearanceFlagWrite
	(*AppearanceFlagWriteOnce)(nil),             // 18: Canary.protobuf.appearances.AppearanceFlagWriteOnce
	(*AppearanceFlagLight)(nil),                 // 19: Canary.protobuf.appearances.AppearanceFlagLight
	(*AppearanceFlagHeight)(nil),                // 20: Canary.protobuf.appearances.AppearanceFlagHeight
	(*AppearanceFlagShift)(nil),                 // 21: Canary.protobuf.appearances.AppearanceFlagShift
	(*AppearanceFlagClothes)(nil),               // 22: Canary.protobuf.appearances.AppearanceFlagClothes
	(*AppearanceFlagDefaultAction)(nil),         // 23: Canary.protobuf.appearances.AppearanceFlagDefaultAction
	(*AppearanceFlagMarket)(nil),                // 24: Canary.protobuf.appearances.AppearanceFlagMarket
	(*AppearanceFlagNPC)(nil),                   // 25: Canary.protobuf.appearances.AppearanceFlagNPC
	(*AppearanceFlagAutomap)(nil),               // 26: Canary.protobuf.appearances.AppearanceFlagAutomap
	(*AppearanceFlagHook)(nil),                  // 27: Canary.protobuf.appearances.AppearanceFlagHook
	(*AppearanceFlagLenshelp)(nil),              // 28: Canary.protobuf.appearances.AppearanceFlagLenshelp
	(*AppearanceFlagChangedToExpire)(nil),       // 29: Canary.protobuf.appearances.AppearanceFlagChangedToExpire
	(*AppearanceFlagCyclopedia)(nil),            // 30: Canary.protobuf.appearances.AppearanceFlagCyclopedia
	(*AppearanceFlagSkillWheelGem)(nil),         // 31: Canary.protobuf.appearances.AppearanceFlagSkillWheelGem
	(*AppearanceFlagProficiency)(nil),           // 32: Canary.protobuf.appearances.AppearanceFlagProficiency
	(*SpecialMeaningAppearanceIds)(nil),         // 33: Canary.protobuf.appearances.SpecialMeaningAppearanceIds
}
var file_appearances_proto_depIdxs = []int32{
	13, // 0: Canary.protobuf.appearances.Appearances.object:type_name -> Canary.protobuf.appearances.Appearance
	13, // 1: Canary.protobuf.appearances.Appearances.outfit:type_name -> Canary.protobuf.appearances.Appearance
	13, // 2: Canary.protobuf.appearances.Appearances.effect:type_name -> Canary.protobuf.appearances.Appearance
	13, // 3: Canary.protobuf.appearances.Appearances.missile:type_name -> Canary.protobuf.appearances.Appearance
	33, // 4: Canary.protobuf.appearances.Appearances.special_meaning_appearance_ids:type_name -> Canary.protobuf.appearances.SpecialMeaningAppearanceIds
	3,  // 5: Canary.protobuf.appearances.SpriteAnimation.loop_type:type_name -> Canary.protobuf.appearances.ANIMATION_LOOP_TYPE
	8,  // 6: Canary.protobuf.appearances.SpriteAnimation.sprite_phase:type_name -> Canary.protobuf.appearances.SpritePhase
	9,  // 7: Canary.protobuf.appearances.SpriteInfo.animation:type_name -> Canary.protobuf.appearances.SpriteAnimation
	10, // 8: Canary.protobuf.appearances.SpriteInfo.bounding_box_per_direction:type_name -> Canary.protobuf.appearances.Box
	5,  // 9: Canary.protobuf.appearances.FrameGroup.fixed_frame_group:type_name -> Canary.protobuf.appearances.FIXED_FRAME_GROUP
	11, // 10: Canary.protobuf.appearances.FrameGroup.sprite_info:type_name -> Canary.protobuf.appearances.SpriteInfo
	12, // 11: Canary.protobuf.appearances.Appearance.frame_group:type_name -> Canary.protobuf.appearances.FrameGroup
	14, // 12: Canary.protobuf.appearances.Appearance.flags:type_name -> Canary.protobuf.appearances.AppearanceFlags
	16, // 13: Canary.protobuf.appearances.AppearanceFlags.bank:type_name -> Canary.protobuf.appearances.AppearanceFlagBank
	17, // 14: Canary.protobuf.appearances.AppearanceFlags.write:type_name -> Canary.protobuf.appearances.AppearanceFlagWrite
	18, // 15: Canary.protobuf.appearances.AppearanceFlags.write_once:type_name -> Canary.protobuf.appearances.AppearanceFlagWriteOnce
	27, // 16: Canary.protobuf.appearances.AppearanceFlags.hook:type_name -> Canary.protobuf.appearances.AppearanceFlagHook
	19, // 17: Canary.protobuf.appearances.AppearanceFlags.light:type_name -> Canary.protobuf.appearances.AppearanceFlagLight
	21, // 18: Canary.protobuf.appearances.AppearanceFlags.shift:type_name -> Canary.protobuf.appearances.AppearanceFlagShift
	20, // 19: Canary.protobuf.appearances.AppearanceFlags.height:type_name -> Canary.protobuf.appearances.AppearanceFlagHeight
	26, // 20: Canary.protobuf.appearances.AppearanceFlags.automap:type_name -> Canary.protobuf.appearances.AppearanceFlagAutomap
	28, // 21: Canary.protobuf.appearances.AppearanceFlags.lenshelp:type_name -> Canary.protobuf.appearances.AppearanceFlagLenshelp
	22, // 22: Canary.protobuf.appearances.AppearanceFlags.clothes:type_name -> Canary.protobuf.appearances.AppearanceFlagClothes
	23, // 23: Canary.protobuf.appearances.AppearanceFlags.default_action:type_name -> Canary.protobuf.appearances.AppearanceFlagDefaultAction
	24, // 24: Canary.protobuf.appearances.AppearanceFlags.market:type_name -> Canary.protobuf.appearances.AppearanceFlagMarket
	25, // 25: Canary.protobuf.appearances.AppearanceFlags.npcsaledata:type_name -> Canary.protobuf.appearances.AppearanceFlagNPC
	29, // 26: Canary.protobuf.appearances.AppearanceFlags.changedtoexpire:type_name -> Canary.protobuf.appearances.AppearanceFlagChangedToExpire
	30, // 27: Canary.protobuf.appearances.AppearanceFlags.cyclopediaitem:type_name -> Canary.protobuf.appearances.AppearanceFlagCyclopedia
	15, // 28: Canary.protobuf.appearances.AppearanceFlags.upgradeclassification:type_name -> Canary.protobuf.appearances.AppearanceFlagUpgradeClassification
	31, // 29: Canary.protobuf.appearances.AppearanceFlags.skillwheel_gem:type_name -> Canary.protobuf.appearances.AppearanceFlagSkillWheelGem
	32, // 30: Canary.protobuf.appearances.AppearanceFlags.proficiency:type_name -> Canary.protobuf.appearances.AppearanceFlagProficiency
	0,  // 31: Canary.protobuf.appearances.AppearanceFlagDefaultAction.action:type_name -> Canary.protobuf.appearances.PLAYER_ACTION
	1,  // 32: Canary.protobuf.appearances.AppearanceFlagMarket.category:type_name -> Canary.protobuf.appearances.ITEM_CATEGORY
	2,  // 33: Canary.protobuf.appearances.AppearanceFlagMarket.restrict_to_profession:type_name -> Canary.protobuf.appearances.PLAYER_PROFESSION
	4,  // 34: Canary.protobuf.appearances.AppearanceFlagHook.direction:type_name -> Canary.protobuf.appearances.HOOK_TYPE
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_appearances_proto_init() }
func file_appearances_proto_init() {
	if File_appearances_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appearances_proto_rawDesc), len(file_appearances_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_appearances_proto_goTypes,
		DependencyIndexes: file_appearances_proto_depIdxs,
		EnumInfos:         file_appearances_proto_enumTypes,
		MessageInfos:      file_appearances_proto_msgTypes,
	}.Build()
	File_appearances_proto = out.File
	file_appearances_proto_goTypes = nil
	file_appearances_proto_depIdxs = nil
}
