package luaengine

import (
	lua "github.com/yuin/gopher-lua"
)

// registerSpellEnums installs the magic-effect, shoot-effect, combat-parameter,
// combat-formula, spell-group and condition-parameter enums used by the spell
// scripts. Values are ported verbatim from the C++ headers:
//   - MagicEffectClasses / ShootType_t (src/utils/utils_definitions.hpp)
//   - CombatParam_t / CombatFormula_t / SpellGroup_t (src/creatures/creatures_definitions.hpp)
//   - ConditionParam_t (src/creatures/creatures_definitions.hpp)
//
// Without these globals the spell scripts reference nil and fail to register.
func registerSpellEnums(L *lua.LState) {
	enums := map[string]lua.LNumber{
		// CombatParam_t (src/creatures/creatures_definitions.hpp)
		"COMBAT_PARAM_TYPE":                  0,
		"COMBAT_PARAM_EFFECT":                1,
		"COMBAT_PARAM_DISTANCEEFFECT":        2,
		"COMBAT_PARAM_BLOCKSHIELD":           3,
		"COMBAT_PARAM_BLOCKARMOR":            4,
		"COMBAT_PARAM_TARGETCASTERORTOPMOST": 5,
		"COMBAT_PARAM_CREATEITEM":            6,
		"COMBAT_PARAM_AGGRESSIVE":            7,
		"COMBAT_PARAM_DISPEL":                8,
		"COMBAT_PARAM_USECHARGES":            9,
		"COMBAT_PARAM_CASTSOUND":             10,
		"COMBAT_PARAM_IMPACTSOUND":           11,
		"COMBAT_PARAM_CHAIN_EFFECT":          12,

		"CALLBACK_PARAM_LEVELMAGICVALUE": 1,
		"CALLBACK_PARAM_SKILLVALUE":      2,
		"CALLBACK_PARAM_TARGETTILE":      3,
		"CALLBACK_PARAM_TARGETCREATURE":  4,
		"CALLBACK_PARAM_CHAINVALUE":      5,
		"CALLBACK_PARAM_CHAINPICKER":     6,

		// CombatFormula_t
		"COMBAT_FORMULA_UNDEFINED":  0,
		"COMBAT_FORMULA_LEVELMAGIC": 1,
		"COMBAT_FORMULA_SKILL":      2,
		"COMBAT_FORMULA_DAMAGE":     3,

		// SpellGroup_t
		"SPELLGROUP_NONE":             0,
		"SPELLGROUP_ATTACK":           1,
		"SPELLGROUP_HEALING":          2,
		"SPELLGROUP_SUPPORT":          3,
		"SPELLGROUP_SPECIAL":          4,
		"SPELLGROUP_CONJURE":          5,
		"SPELLGROUP_CRIPPLING":        6,
		"SPELLGROUP_FOCUS":            7,
		"SPELLGROUP_ULTIMATESTRIKES":  8,
		"SPELLGROUP_BURSTS_OF_NATURE": 9,
		"SPELLGROUP_GREAT_BEAMS":      10,
		"SPELLGROUP_VIRTUE":           11,

		// ConditionParam_t (subset referenced by spell scripts). Values from
		// src/creatures/creatures_definitions.hpp. Captured but not applied.
		"CONDITION_PARAM_OWNER":          1,
		"CONDITION_PARAM_TICKS":          2,
		"CONDITION_PARAM_HEALTHGAIN":     4,
		"CONDITION_PARAM_HEALTHTICKS":    5,
		"CONDITION_PARAM_MANAGAIN":       6,
		"CONDITION_PARAM_MANATICKS":      7,
		"CONDITION_PARAM_DELAYED":        8,
		"CONDITION_PARAM_SPEED":          9,
		"CONDITION_PARAM_PERIODICDAMAGE": 30,
		"CONDITION_PARAM_SUBID":          20,

		// SpellType_t
		"SPELL_INSTANT": 1,
		"SPELL_RUNE":    2,
	}

	for _, e := range append(magicEffectEnums(), shootEffectEnums()...) {
		L.SetGlobal(e.name, lua.LNumber(e.value))
	}
	for k, v := range enums {
		L.SetGlobal(k, v)
	}
}

type namedEnum struct {
	name  string
	value int
}

// magicEffectEnums lists MagicEffectClasses (src/utils/utils_definitions.hpp).
func magicEffectEnums() []namedEnum {
	return []namedEnum{
		{"CONST_ME_NONE", 0}, {"CONST_ME_DRAWBLOOD", 1}, {"CONST_ME_LOSEENERGY", 2},
		{"CONST_ME_POFF", 3}, {"CONST_ME_BLOCKHIT", 4}, {"CONST_ME_EXPLOSIONAREA", 5},
		{"CONST_ME_EXPLOSIONHIT", 6}, {"CONST_ME_FIREAREA", 7}, {"CONST_ME_YELLOW_RINGS", 8},
		{"CONST_ME_GREEN_RINGS", 9}, {"CONST_ME_HITAREA", 10}, {"CONST_ME_TELEPORT", 11},
		{"CONST_ME_ENERGYHIT", 12}, {"CONST_ME_MAGIC_BLUE", 13}, {"CONST_ME_MAGIC_RED", 14},
		{"CONST_ME_MAGIC_GREEN", 15}, {"CONST_ME_HITBYFIRE", 16}, {"CONST_ME_HITBYPOISON", 17},
		{"CONST_ME_MORTAREA", 18}, {"CONST_ME_SOUND_GREEN", 19}, {"CONST_ME_SOUND_RED", 20},
		{"CONST_ME_POISONAREA", 21}, {"CONST_ME_SOUND_YELLOW", 22}, {"CONST_ME_SOUND_PURPLE", 23},
		{"CONST_ME_SOUND_BLUE", 24}, {"CONST_ME_SOUND_WHITE", 25}, {"CONST_ME_BUBBLES", 26},
		{"CONST_ME_CRAPS", 27}, {"CONST_ME_GIFT_WRAPS", 28}, {"CONST_ME_FIREWORK_YELLOW", 29},
		{"CONST_ME_FIREWORK_RED", 30}, {"CONST_ME_FIREWORK_BLUE", 31}, {"CONST_ME_STUN", 32},
		{"CONST_ME_SLEEP", 33}, {"CONST_ME_WATERCREATURE", 34}, {"CONST_ME_GROUNDSHAKER", 35},
		{"CONST_ME_HEARTS", 36}, {"CONST_ME_FIREATTACK", 37}, {"CONST_ME_ENERGYAREA", 38},
		{"CONST_ME_SMALLCLOUDS", 39}, {"CONST_ME_HOLYDAMAGE", 40}, {"CONST_ME_BIGCLOUDS", 41},
		{"CONST_ME_ICEAREA", 42}, {"CONST_ME_ICETORNADO", 43}, {"CONST_ME_ICEATTACK", 44},
		{"CONST_ME_STONES", 45}, {"CONST_ME_SMALLPLANTS", 46}, {"CONST_ME_CARNIPHILA", 47},
		{"CONST_ME_PURPLEENERGY", 48}, {"CONST_ME_YELLOWENERGY", 49}, {"CONST_ME_HOLYAREA", 50},
		{"CONST_ME_BIGPLANTS", 51}, {"CONST_ME_CAKE", 52}, {"CONST_ME_GIANTICE", 53},
		{"CONST_ME_WATERSPLASH", 54}, {"CONST_ME_PLANTATTACK", 55}, {"CONST_ME_TUTORIALARROW", 56},
		{"CONST_ME_TUTORIALSQUARE", 57}, {"CONST_ME_MIRRORHORIZONTAL", 58}, {"CONST_ME_MIRRORVERTICAL", 59},
		{"CONST_ME_SKULLHORIZONTAL", 60}, {"CONST_ME_SKULLVERTICAL", 61}, {"CONST_ME_ASSASSIN", 62},
		{"CONST_ME_STEPSHORIZONTAL", 63}, {"CONST_ME_BLOODYSTEPS", 64}, {"CONST_ME_STEPSVERTICAL", 65},
		{"CONST_ME_YALAHARIGHOST", 66}, {"CONST_ME_BATS", 67}, {"CONST_ME_SMOKE", 68},
		{"CONST_ME_INSECTS", 69}, {"CONST_ME_DRAGONHEAD", 70}, {"CONST_ME_ORCSHAMAN", 71},
		{"CONST_ME_ORCSHAMAN_FIRE", 72}, {"CONST_ME_THUNDER", 73}, {"CONST_ME_FERUMBRAS", 74},
		{"CONST_ME_CONFETTI_HORIZONTAL", 75}, {"CONST_ME_CONFETTI_VERTICAL", 76},
		{"CONST_ME_BLACKSMOKE", 158}, {"CONST_ME_REDSMOKE", 167}, {"CONST_ME_YELLOWSMOKE", 168},
		{"CONST_ME_GREENSMOKE", 169}, {"CONST_ME_PURPLESMOKE", 170}, {"CONST_ME_EARLY_THUNDER", 171},
		{"CONST_ME_RAGIAZ_BONECAPSULE", 172}, {"CONST_ME_CRITICAL_DAMAGE", 173},
		{"CONST_ME_PLUNGING_FISH", 175}, {"CONST_ME_BLUE_ENERGY_SPARK", 176},
		{"CONST_ME_ORANGE_ENERGY_SPARK", 177}, {"CONST_ME_GREEN_ENERGY_SPARK", 178},
		{"CONST_ME_PINK_ENERGY_SPARK", 179}, {"CONST_ME_WHITE_ENERGY_SPARK", 180},
		{"CONST_ME_YELLOW_ENERGY_SPARK", 181}, {"CONST_ME_MAGIC_POWDER", 182},
		{"CONST_ME_PIXIE_EXPLOSION", 184}, {"CONST_ME_PIXIE_COMING", 185}, {"CONST_ME_PIXIE_GOING", 186},
		{"CONST_ME_STORM", 188}, {"CONST_ME_STONE_STORM", 189}, {"CONST_ME_BLUE_GHOST", 191},
		{"CONST_ME_PINK_VORTEX", 193}, {"CONST_ME_TREASURE_MAP", 194}, {"CONST_ME_PINK_BEAM", 195},
		{"CONST_ME_GREEN_FIREWORKS", 196}, {"CONST_ME_ORANGE_FIREWORKS", 197},
		{"CONST_ME_PINK_FIREWORKS", 198}, {"CONST_ME_BLUE_FIREWORKS", 199},
		{"CONST_ME_SUPREME_CUBE", 201}, {"CONST_ME_BLACK_BLOOD", 202}, {"CONST_ME_PRISMATIC_SPARK", 203},
		{"CONST_ME_THAIAN", 204}, {"CONST_ME_THAIAN_GHOST", 205}, {"CONST_ME_GHOST_SMOKE", 206},
		{"CONST_ME_WATER_BLOCK_FLOATING", 208}, {"CONST_ME_WATER_BLOCK", 209}, {"CONST_ME_ROOTS", 210},
		{"CONST_ME_GHOSTLY_SCRATCH", 213}, {"CONST_ME_GHOSTLY_BITE", 214}, {"CONST_ME_BIG_SCRATCH", 215},
		{"CONST_ME_SLASH", 216}, {"CONST_ME_BITE", 217}, {"CONST_ME_CHIVALRIOUS_CHALLENGE", 219},
		{"CONST_ME_DIVINE_DAZZLE", 220}, {"CONST_ME_ELECTRICALSPARK", 221}, {"CONST_ME_PURPLETELEPORT", 222},
		{"CONST_ME_REDTELEPORT", 223}, {"CONST_ME_ORANGETELEPORT", 224}, {"CONST_ME_GREYTELEPORT", 225},
		{"CONST_ME_LIGHTBLUETELEPORT", 226}, {"CONST_ME_FATAL", 230}, {"CONST_ME_DODGE", 231},
		{"CONST_ME_HOURGLASS", 232}, {"CONST_ME_DAZZLING", 233}, {"CONST_ME_SPARKLING", 234},
		{"CONST_ME_FERUMBRAS_1", 235}, {"CONST_ME_GAZHARAGOTH", 236}, {"CONST_ME_MAD_MAGE", 237},
		{"CONST_ME_HORESTIS", 238}, {"CONST_ME_DEVOVORGA", 239}, {"CONST_ME_FERUMBRAS_2", 240},
		{"CONST_ME_WHITE_SMOKE", 241}, {"CONST_ME_WHITE_SMOKES", 242}, {"CONST_ME_WATER_DROP", 243},
		{"CONST_ME_AVATAR_APPEAR", 244}, {"CONST_ME_DIVINE_GRENADE", 245}, {"CONST_ME_DIVINE_EMPOWERMENT", 246},
		{"CONST_ME_WATER_FLOATING_THRASH", 247}, {"CONST_ME_AGONY", 249}, {"CONST_ME_LOOT_HIGHLIGHT", 252},
		{"CONST_ME_MELTING_CREAM", 263}, {"CONST_ME_REAPER", 264}, {"CONST_ME_POWERFUL_HEARTS", 265},
		{"CONST_ME_CREAM", 266}, {"CONST_ME_GENTLE_BUBBLE", 267}, {"CONST_ME_STARBURST", 268},
		{"CONST_ME_SIRUP", 269}, {"CONST_ME_CACAO", 270}, {"CONST_ME_CANDY_FLOSS", 271},
		{"CONST_ME_HITAREA_GREEN", 272}, {"CONST_ME_HITAREA_RED", 273}, {"CONST_ME_HITAREA_BLUE", 274},
		{"CONST_ME_HITAREA_ORANGE", 275}, {"CONST_ME_WHIRLWIND_BLOW_WHITE", 276},
		{"CONST_ME_WHIRLWIND_BLOW_GREEN", 277}, {"CONST_ME_WHIRLWIND_BLOW_PINK", 278},
		{"CONST_ME_PULSE_WHITE", 279}, {"CONST_ME_PULSE_GREEN", 280}, {"CONST_ME_PULSE_PINK", 281},
		{"CONST_ME_CLAW_WHITE", 282}, {"CONST_ME_CLAW_GREEN", 283}, {"CONST_ME_CLAW_PINK", 284},
		{"CONST_ME_BLOW_WHITE", 285}, {"CONST_ME_BLOW_GREEN", 286}, {"CONST_ME_BLOW_BLUE", 287},
		{"CONST_ME_BLOW_PINK", 288}, {"CONST_ME_OUTBURST_WHITE", 289}, {"CONST_ME_OUTBURST_GREEN", 290},
		{"CONST_ME_OUTBURST_YELLOW", 291}, {"CONST_ME_INK_EXPLOSION", 292}, {"CONST_ME_PAPER_PLANE", 293},
		{"CONST_ME_WOODEN_STAKES", 294}, {"CONST_ME_FIRE_SPARKLES", 295}, {"CONST_ME_OPENING_MAGIC_BOOK", 296},
		{"CONST_ME_GRAY_ELECTRIC_SPARK", 301}, {"CONST_ME_GREEN_ELECTRIC_SPARK", 302},
		{"CONST_ME_PURPLE_ELECTRIC_SPARK", 303},
	}
}

// shootEffectEnums lists ShootType_t (src/utils/utils_definitions.hpp).
func shootEffectEnums() []namedEnum {
	return []namedEnum{
		{"CONST_ANI_NONE", 0}, {"CONST_ANI_SPEAR", 1}, {"CONST_ANI_BOLT", 2}, {"CONST_ANI_ARROW", 3},
		{"CONST_ANI_FIRE", 4}, {"CONST_ANI_ENERGY", 5}, {"CONST_ANI_POISONARROW", 6},
		{"CONST_ANI_BURSTARROW", 7}, {"CONST_ANI_THROWINGSTAR", 8}, {"CONST_ANI_THROWINGKNIFE", 9},
		{"CONST_ANI_SMALLSTONE", 10}, {"CONST_ANI_DEATH", 11}, {"CONST_ANI_LARGEROCK", 12},
		{"CONST_ANI_SNOWBALL", 13}, {"CONST_ANI_POWERBOLT", 14}, {"CONST_ANI_POISON", 15},
		{"CONST_ANI_INFERNALBOLT", 16}, {"CONST_ANI_HUNTINGSPEAR", 17}, {"CONST_ANI_ENCHANTEDSPEAR", 18},
		{"CONST_ANI_REDSTAR", 19}, {"CONST_ANI_GREENSTAR", 20}, {"CONST_ANI_ROYALSPEAR", 21},
		{"CONST_ANI_SNIPERARROW", 22}, {"CONST_ANI_ONYXARROW", 23}, {"CONST_ANI_PIERCINGBOLT", 24},
		{"CONST_ANI_WHIRLWINDSWORD", 25}, {"CONST_ANI_WHIRLWINDAXE", 26}, {"CONST_ANI_WHIRLWINDCLUB", 27},
		{"CONST_ANI_ETHEREALSPEAR", 28}, {"CONST_ANI_ICE", 29}, {"CONST_ANI_EARTH", 30},
		{"CONST_ANI_HOLY", 31}, {"CONST_ANI_SUDDENDEATH", 32}, {"CONST_ANI_FLASHARROW", 33},
		{"CONST_ANI_FLAMMINGARROW", 34}, {"CONST_ANI_SHIVERARROW", 35}, {"CONST_ANI_ENERGYBALL", 36},
		{"CONST_ANI_SMALLICE", 37}, {"CONST_ANI_SMALLHOLY", 38}, {"CONST_ANI_SMALLEARTH", 39},
		{"CONST_ANI_EARTHARROW", 40}, {"CONST_ANI_EXPLOSION", 41}, {"CONST_ANI_CAKE", 42},
		{"CONST_ANI_TARSALARROW", 44}, {"CONST_ANI_VORTEXBOLT", 45}, {"CONST_ANI_PRISMATICBOLT", 48},
		{"CONST_ANI_CRYSTALLINEARROW", 49}, {"CONST_ANI_DRILLBOLT", 50}, {"CONST_ANI_ENVENOMEDARROW", 51},
		{"CONST_ANI_GLOOTHSPEAR", 53}, {"CONST_ANI_SIMPLEARROW", 54}, {"CONST_ANI_LEAFSTAR", 56},
		{"CONST_ANI_DIAMONDARROW", 57}, {"CONST_ANI_SPECTRALBOLT", 58}, {"CONST_ANI_ROYALSTAR", 59},
		{"CONST_ANI_CANDYCANE", 61}, {"CONST_ANI_CHERRYBOMB", 62}, {"CONST_ANI_WEAPONTYPE", 254},
	}
}
