package luaengine

import (
	lua "github.com/yuin/gopher-lua"
)

// RegisterEnums registers the major Tibia global enums in the given Lua state.
func RegisterEnums(L *lua.LState) {
	enums := map[string]lua.LNumber{
		// Slots
		"CONST_SLOT_FIRST": 1, // = CONST_SLOT_HEAD
		// MAX_LOOTCHANCE (src/utils/const.hpp:12, registered at
		// lua_enums.cpp:166). Loot chances in monster data are out of this, and
		// getLootRandom does math.random(0, MAX_LOOTCHANCE) — without it the whole
		// monsterOnDropLoot chain errors out and nothing drops.
		"MAX_LOOTCHANCE": 100000,

		// SpeechBubble_t (src/creatures/creatures_definitions.hpp:333). Every npc
		// script assigns one of these to npcConfig.speechBubble — 1032 uses across
		// the datapack — and an undefined Lua global is nil, not an error, so the
		// bubble was silently dropped for every NPC.
		// SPEECHBUBBLE_BANKER intentionally aliases TRADE, as upstream does.
		"SPEECHBUBBLE_NONE":        0,
		"SPEECHBUBBLE_NORMAL":      1,
		"SPEECHBUBBLE_TRADE":       2,
		"SPEECHBUBBLE_QUEST":       3,
		"SPEECHBUBBLE_QUESTTRADER": 4,
		"SPEECHBUBBLE_SAILOR":      5,
		"SPEECHBUBBLE_BANKER":      2,
		"SPEECHBUBBLE_HIRELING":    7,

		"CONST_SLOT_HEAD":        1,
		"CONST_SLOT_NECKLACE":    2,
		"CONST_SLOT_BACKPACK":    3,
		"CONST_SLOT_ARMOR":       4,
		"CONST_SLOT_RIGHT":       5,
		"CONST_SLOT_LEFT":        6,
		"CONST_SLOT_LEGS":        7,
		"CONST_SLOT_FEET":        8,
		"CONST_SLOT_RING":        9,
		"CONST_SLOT_AMMO":        10,
		"CONST_SLOT_STORE_INBOX": 11,
		"CONST_SLOT_LAST":        11, // = CONST_SLOT_STORE_INBOX

		// Account types
		"ACCOUNT_TYPE_NORMAL":           1,
		"ACCOUNT_TYPE_TUTOR":            2,
		"ACCOUNT_TYPE_SENIORTUTOR":      3,
		"ACCOUNT_TYPE_GAMEMASTER":       4,
		"ACCOUNT_TYPE_COMMUNITYMANAGER": 5,
		"ACCOUNT_TYPE_GOD":              6,

		// Speak classes (talk types). NPC dialogue gates keyword processing on
		// TALKTYPE_PRIVATE_PN (player→NPC), so these MUST exist as globals — a
		// nil TALKTYPE_PRIVATE_PN silently kills all post-greeting interaction.
		"TALKTYPE_SAY":                1,
		"TALKTYPE_WHISPER":            2,
		"TALKTYPE_YELL":               3,
		"TALKTYPE_PRIVATE_FROM":       4,
		"TALKTYPE_PRIVATE_TO":         5,
		"TALKTYPE_CHANNEL_MANAGEMENT": 6,
		"TALKTYPE_CHANNEL_Y":          7,
		"TALKTYPE_CHANNEL_O":          8,
		"TALKTYPE_SPELL_USE":          9,
		"TALKTYPE_PRIVATE_NP":         10,
		"TALKTYPE_NPC_UNKNOWN":        11,
		"TALKTYPE_PRIVATE_PN":         12,
		"TALKTYPE_BROADCAST":          13,
		"TALKTYPE_CHANNEL_R1":         14,
		"TALKTYPE_PRIVATE_RED_FROM":   15,
		"TALKTYPE_PRIVATE_RED_TO":     16,
		"TALKTYPE_MONSTER_SAY":        36,
		"TALKTYPE_MONSTER_YELL":       37,
		"TALKTYPE_CHANNEL_R2":         0xFF,

		// Messages
		"MESSAGE_GAMEMASTER_CONSOLE": 13,
		"MESSAGE_LOGIN":              17,

		// Groups
		"GROUP_TYPE_NONE":             0,
		"GROUP_TYPE_NORMAL":           1,
		"GROUP_TYPE_TUTOR":            2,
		"GROUP_TYPE_SENIORTUTOR":      3,
		"GROUP_TYPE_GAMEMASTER":       4,
		"GROUP_TYPE_COMMUNITYMANAGER": 5,
		"GROUP_TYPE_GOD":              6,
		"MESSAGE_ADMINISTRATOR":       18,
		"MESSAGE_EVENT_ADVANCE":       19,
		"MESSAGE_GAME_HIGHLIGHT":      20,
		"MESSAGE_FAILURE":             21,
		"MESSAGE_LOOK":                22,
		"MESSAGE_DAMAGE_DEALT":        23,
		"MESSAGE_DAMAGE_RECEIVED":     24,
		"MESSAGE_HEALED":              25,
		"MESSAGE_EXPERIENCE":          26,
		"MESSAGE_DAMAGE_OTHERS":       27,
		"MESSAGE_HEALED_OTHERS":       28,
		"MESSAGE_EXPERIENCE_OTHERS":   29,
		"MESSAGE_STATUS":              30,
		"MESSAGE_LOOT":                31,
		"MESSAGE_TRADE":               32,
		"MESSAGE_GUILD":               33,
		"MESSAGE_PARTY_MANAGEMENT":    34,
		"MESSAGE_PARTY":               35,
		"MESSAGE_LAST_OLDPROTOCOL":    37,
		"MESSAGE_REPORT":              38,
		"MESSAGE_HOTKEY_PRESSED":      39,
		"MESSAGE_TUTORIAL_HINT":       40,
		"MESSAGE_THANK_YOU":           41,
		"MESSAGE_MARKET":              42,
		"MESSAGE_MANA":                43,
		"MESSAGE_BEYOND_LAST":         44,
		"MESSAGE_ATTENTION":           48,
		"MESSAGE_BOOSTED_CREATURE":    49,
		"MESSAGE_OFFLINE_TRAINING":    50,
		"MESSAGE_TRANSACTION":         51,
		"MESSAGE_POTION":              52,
		"MESSAGE_STATUS_CONSOLE_BLUE": 30, // alias

		// Combat Types (CombatType_t, src/creatures/creatures_definitions.hpp).
		// These are sequential C++ enum values, not bitflags; the setParameter
		// binding maps them to the internal combat.CombatType flags.
		"COMBAT_PHYSICALDAMAGE":  0,
		"COMBAT_FIREDAMAGE":      1,
		"COMBAT_EARTHDAMAGE":     2,
		"COMBAT_ENERGYDAMAGE":    3,
		"COMBAT_UNDEFINEDDAMAGE": 4,
		"COMBAT_LIFEDRAIN":       5,
		"COMBAT_MANADRAIN":       6,
		"COMBAT_HEALING":         7,
		"COMBAT_DROWNDAMAGE":     8,
		"COMBAT_ICEDAMAGE":       9,
		"COMBAT_HOLYDAMAGE":      10,
		"COMBAT_DEATHDAMAGE":     11,
		"COMBAT_AGONYDAMAGE":     12,
		"COMBAT_NEUTRALDAMAGE":   13,
		"COMBAT_NONE":            255,

		// ItemTypes_t (items_definitions.hpp:140). These were renumbered 0..9, so
		// no comparison against ItemType:getType could ever match, and the types
		// the datapack actually asks about (ARMOR, HELMET, POTION, ...) were absent.
		"ITEM_TYPE_NONE":            0,
		"ITEM_TYPE_ARMOR":           1,
		"ITEM_TYPE_AMULET":          2,
		"ITEM_TYPE_BOOTS":           3,
		"ITEM_TYPE_CONTAINER":       4,
		"ITEM_TYPE_DECORATION":      5,
		"ITEM_TYPE_FOOD":            6,
		"ITEM_TYPE_HELMET":          7,
		"ITEM_TYPE_LEGS":            8,
		"ITEM_TYPE_OTHER":           9,
		"ITEM_TYPE_POTION":          10,
		"ITEM_TYPE_RING":            11,
		"ITEM_TYPE_RUNE":            12,
		"ITEM_TYPE_SHIELD":          13,
		"ITEM_TYPE_TOOLS":           14,
		"ITEM_TYPE_VALUABLE":        15,
		"ITEM_TYPE_AMMO":            16,
		"ITEM_TYPE_AXE":             17,
		"ITEM_TYPE_CLUB":            18,
		"ITEM_TYPE_DISTANCE":        19,
		"ITEM_TYPE_SWORD":           20,
		"ITEM_TYPE_WAND":            21,
		"ITEM_TYPE_PREMIUMSCROLL":   22,
		"ITEM_TYPE_TIBIACOIN":       23,
		"ITEM_TYPE_CREATUREPRODUCT": 24,
		"ITEM_TYPE_QUIVER":          25,
		"ITEM_TYPE_SOULCORES":       26,
		"ITEM_TYPE_FIST":            27,
		"ITEM_TYPE_DEPOT":           28,
		"ITEM_TYPE_MAILBOX":         29,
		"ITEM_TYPE_TRASHHOLDER":     30,
		"ITEM_TYPE_DOOR":            31,
		"ITEM_TYPE_MAGICFIELD":      32,
		"ITEM_TYPE_TELEPORT":        33,
		"ITEM_TYPE_BED":             34,
		"ITEM_TYPE_KEY":             35,
		"ITEM_TYPE_SUPPLY":          36,
		"ITEM_TYPE_REWARDCHEST":     37,
		"ITEM_TYPE_CARPET":          38,
		"ITEM_TYPE_RETRIEVE":        39,
		"ITEM_TYPE_GOLD":            40,
		"ITEM_TYPE_UNASSIGNED":      41,
		"ITEM_TYPE_LADDER":          42,
		"ITEM_TYPE_DUMMY":           43,
		"ITEM_TYPE_LAST":            44,

		// Item Attributes
		"ITEM_ATTRIBUTE_NONE":                 0,
		"ITEM_ATTRIBUTE_ACTIONID":             1,
		"ITEM_ATTRIBUTE_UNIQUEID":             2,
		"ITEM_ATTRIBUTE_DESCRIPTION":          3,
		"ITEM_ATTRIBUTE_TEXT":                 4,
		"ITEM_ATTRIBUTE_DATE":                 5,
		"ITEM_ATTRIBUTE_WRITER":               6,
		"ITEM_ATTRIBUTE_NAME":                 7,
		"ITEM_ATTRIBUTE_ARTICLE":              8,
		"ITEM_ATTRIBUTE_PLURALNAME":           9,
		"ITEM_ATTRIBUTE_WEIGHT":               10,
		"ITEM_ATTRIBUTE_ATTACK":               11,
		"ITEM_ATTRIBUTE_DEFENSE":              12,
		"ITEM_ATTRIBUTE_EXTRADEFENSE":         13,
		"ITEM_ATTRIBUTE_ARMOR":                14,
		"ITEM_ATTRIBUTE_HITCHANCE":            15,
		"ITEM_ATTRIBUTE_SHOOTRANGE":           16,
		"ITEM_ATTRIBUTE_OWNER":                17,
		"ITEM_ATTRIBUTE_DURATION":             18,
		"ITEM_ATTRIBUTE_DECAYSTATE":           19,
		"ITEM_ATTRIBUTE_CORPSEOWNER":          20,
		"ITEM_ATTRIBUTE_CHARGES":              21,
		"ITEM_ATTRIBUTE_FLUIDTYPE":            22,
		"ITEM_ATTRIBUTE_DOORID":               23,
		"ITEM_ATTRIBUTE_SPECIAL":              24,
		"ITEM_ATTRIBUTE_IMBUEMENT_SLOT":       25,
		"ITEM_ATTRIBUTE_OPENCONTAINER":        26,
		"ITEM_ATTRIBUTE_QUICKLOOTCONTAINER":   27,
		"ITEM_ATTRIBUTE_DURATION_TIMESTAMP":   28,
		"ITEM_ATTRIBUTE_AMOUNT":               29,
		"ITEM_ATTRIBUTE_TIER":                 30,
		"ITEM_ATTRIBUTE_STORE":                31,
		"ITEM_ATTRIBUTE_CUSTOM":               32,
		"ITEM_ATTRIBUTE_LOOTMESSAGE_SUFFIX":   33,
		"ITEM_ATTRIBUTE_STORE_INBOX_CATEGORY": 34,
		"ITEM_ATTRIBUTE_OBTAINCONTAINER":      35,
		"ITEM_ATTRIBUTE_AUGMENTS":             36,
		"ITEM_ATTRIBUTE_MANTRA":               37,

		// Item Coin IDs
		"ITEM_GOLD_COIN":     3031,
		"ITEM_PLATINUM_COIN": 3035,
		"ITEM_CRYSTAL_COIN":  3043,

		// skills_t (creatures_definitions.hpp:466). These were every value shifted
		// up by one, so a script asking for SKILL_FIST indexed the club slot —
		// player:getSkillLevel and friends index game.Skills directly, and
		// game.SkillFist is 0.
		"SKILL_NONE":                -1,
		"SKILL_FIST":                0,
		"SKILL_CLUB":                1,
		"SKILL_SWORD":               2,
		"SKILL_AXE":                 3,
		"SKILL_DISTANCE":            4,
		"SKILL_SHIELD":              5,
		"SKILL_FISHING":             6,
		"SKILL_CRITICAL_HIT_CHANCE": 7,
		"SKILL_CRITICAL_HIT_DAMAGE": 8,
		"SKILL_LIFE_LEECH_CHANCE":   9,
		"SKILL_LIFE_LEECH_AMOUNT":   10,
		"SKILL_MANA_LEECH_CHANCE":   11,
		"SKILL_MANA_LEECH_AMOUNT":   12,
		"SKILL_MAGLEVEL":            13,
		"SKILL_LEVEL":               14,

		// Player Pronouns
		"PLAYERPRONOUN_UNSET": 0,
		"PLAYERPRONOUN_THEY":  1,
		"PLAYERPRONOUN_SHE":   2,
		"PLAYERPRONOUN_HE":    3,
		"PLAYERPRONOUN_ZE":    4,
		"PLAYERPRONOUN_NAME":  5,

		// Concoction IDs
		"Concoction_KooldownAid":           36723,
		"Concoction_StaminaExtension":      36725,
		"Concoction_StrikeEnhancement":     36724,
		"Concoction_CharmUpgrade":          36726,
		"Concoction_WealthDuplex":          36727,
		"Concoction_BestiaryBetterment":    36728,
		"Concoction_FireResilience":        36729,
		"Concoction_IceResilience":         36730,
		"Concoction_EarthResilience":       36731,
		"Concoction_EnergyResilience":      36732,
		"Concoction_HolyResilience":        36733,
		"Concoction_DeathResilience":       36734,
		"Concoction_PhysicalResilience":    36735,
		"Concoction_FireAmplification":     36736,
		"Concoction_IceAmplification":      36737,
		"Concoction_EarthAmplification":    36738,
		"Concoction_EnergyAmplification":   36739,
		"Concoction_HolyAmplification":     36740,
		"Concoction_DeathAmplification":    36741,
		"Concoction_PhysicalAmplification": 36742,

		// World Types
		"WORLD_TYPE_NO_PVP":       1,
		"WORLD_TYPE_PVP":          2,
		"WORLD_TYPE_PVP_ENFORCED": 3,

		// TileFlags_t (items_definitions.hpp:443). The map loader now translates
		// the OTBM bits into these, as IOMap does, so hasFlag agrees with upstream.
		// TILESTATE_HOUSE is deliberately absent: it does not exist in C++ either,
		// where hasFlag(nil) reads the flag as 0 and returns false.
		"TILESTATE_NONE":                      0,
		"TILESTATE_FLOORCHANGE_DOWN":          1 << 0,
		"TILESTATE_FLOORCHANGE_NORTH":         1 << 1,
		"TILESTATE_FLOORCHANGE_SOUTH":         1 << 2,
		"TILESTATE_FLOORCHANGE_EAST":          1 << 3,
		"TILESTATE_FLOORCHANGE_WEST":          1 << 4,
		"TILESTATE_FLOORCHANGE_SOUTH_ALT":     1 << 5,
		"TILESTATE_FLOORCHANGE_EAST_ALT":      1 << 6,
		"TILESTATE_PROTECTIONZONE":            1 << 7,
		"TILESTATE_NOPVPZONE":                 1 << 8,
		"TILESTATE_NOLOGOUT":                  1 << 9,
		"TILESTATE_PVPZONE":                   1 << 10,
		"TILESTATE_TELEPORT":                  1 << 11,
		"TILESTATE_MAGICFIELD":                1 << 12,
		"TILESTATE_MAILBOX":                   1 << 13,
		"TILESTATE_TRASHHOLDER":               1 << 14,
		"TILESTATE_BED":                       1 << 15,
		"TILESTATE_DEPOT":                     1 << 16,
		"TILESTATE_BLOCKSOLID":                1 << 17,
		"TILESTATE_BLOCKPATH":                 1 << 18,
		"TILESTATE_IMMOVABLEBLOCKSOLID":       1 << 19,
		"TILESTATE_IMMOVABLEBLOCKPATH":        1 << 20,
		"TILESTATE_IMMOVABLENOFIELDBLOCKPATH": 1 << 21,
		"TILESTATE_NOFIELDBLOCKPATH":          1 << 22,
		"TILESTATE_SUPPORTS_HANGABLE":         1 << 23,
		"TILESTATE_MOVABLE":                   1 << 24,
		"TILESTATE_ISHORIZONTAL":              1 << 25,
		"TILESTATE_ISVERTICAL":                1 << 26,
		"TILESTATE_BLOCKPROJECTILE":           1 << 27,
		"TILESTATE_HASHEIGHT":                 1 << 28,
		"TILESTATE_FLOORCHANGE":               (1 << 0) | (1 << 1) | (1 << 2) | (1 << 3) | (1 << 4) | (1 << 5) | (1 << 6),

		// Item / Tile Properties (CONST_PROP_*)
		"CONST_PROP_BLOCKSOLID":                0,
		"CONST_PROP_HASHEIGHT":                 1,
		"CONST_PROP_BLOCKPROJECTILE":           2,
		"CONST_PROP_BLOCKPATH":                 3,
		"CONST_PROP_ISVERTICAL":                4,
		"CONST_PROP_ISHORIZONTAL":              5,
		"CONST_PROP_MOVABLE":                   6,
		"CONST_PROP_IMMOVABLEBLOCKSOLID":       7,
		"CONST_PROP_IMMOVABLEBLOCKPATH":        8,
		"CONST_PROP_IMMOVABLENOFIELDBLOCKPATH": 9,
		"CONST_PROP_NOFIELDBLOCKPATH":          10,
		"CONST_PROP_SUPPORTHANGABLE":           11,

		// Zones
		"ZONE_PROTECTION": 0,
		"ZONE_NOPVP":      1,
		"ZONE_PVP":        2,
		"ZONE_NOLOGOUT":   3,
		"ZONE_NORMAL":     4,

		// Bestiary Races (creatures_definitions.hpp BestiaryType_t). The client
		// groups the cyclopedia by these ids, so they must match C++ exactly.
		"BESTY_RACE_NONE":              0,
		"BESTY_RACE_AMPHIBIC":          1,
		"BESTY_RACE_AQUATIC":           2,
		"BESTY_RACE_BIRD":              3,
		"BESTY_RACE_CONSTRUCT":         4,
		"BESTY_RACE_DEMON":             5,
		"BESTY_RACE_DRAGON":            6,
		"BESTY_RACE_ELEMENTAL":         7,
		"BESTY_RACE_FEY":               8,
		"BESTY_RACE_GIANT":             9,
		"BESTY_RACE_HUMAN":             10,
		"BESTY_RACE_HUMANOID":          11,
		"BESTY_RACE_LYCANTHROPE":       12,
		"BESTY_RACE_MAGICAL":           13,
		"BESTY_RACE_MAMMAL":            14,
		"BESTY_RACE_PLANT":             15,
		"BESTY_RACE_REPTILE":           16,
		"BESTY_RACE_SLIME":             17,
		"BESTY_RACE_UNDEAD":            18,
		"BESTY_RACE_VERMIN":            19,
		"BESTY_RACE_EXTRA_DIMENSIONAL": 20,
		"BESTY_RACE_INKBORN":           21,

		// Creature Types
		"CREATURETYPE_PLAYER":        0,
		"CREATURETYPE_MONSTER":       1,
		"CREATURETYPE_NPC":           2,
		"CREATURETYPE_SUMMON_OWN":    3,
		"CREATURETYPE_SUMMON_OTHERS": 4,

		// Directions
		"DIRECTION_NORTH":         0,
		"DIRECTION_EAST":          1,
		"DIRECTION_SOUTH":         2,
		"DIRECTION_WEST":          3,
		"DIRECTION_DIAGONAL_MASK": 4,
		"DIRECTION_SOUTHWEST":     4,
		"DIRECTION_SOUTHEAST":     5,
		"DIRECTION_NORTHWEST":     6,
		"DIRECTION_NORTHEAST":     7,

		// Return values
		// ReturnValue (items_definitions.hpp:36), all 90 values. Only four were
		// defined and they were numbered 0..3, where upstream has NOTPOSSIBLE at 4,
		// NOTENOUGHROOM at 5 and PLAYERISPZLOCKED at 6 — the datapack compares
		// against these in 69 places.
		"RETURNVALUE_NOERROR":                                     0,
		"RETURNVALUE_NOTBOUGHTINSTORE":                            1,
		"RETURNVALUE_ITEMCANNOTBEMOVEDTHERE":                      2,
		"RETURNVALUE_ITEMCANNOTBEMOVEDPOUCH":                      3,
		"RETURNVALUE_NOTPOSSIBLE":                                 4,
		"RETURNVALUE_NOTENOUGHROOM":                               5,
		"RETURNVALUE_PLAYERISPZLOCKED":                            6,
		"RETURNVALUE_PLAYERISNOTINVITED":                          7,
		"RETURNVALUE_CANNOTTHROW":                                 8,
		"RETURNVALUE_THEREISNOWAY":                                9,
		"RETURNVALUE_DESTINATIONOUTOFREACH":                       10,
		"RETURNVALUE_CREATUREBLOCK":                               11,
		"RETURNVALUE_NOTMOVABLE":                                  12,
		"RETURNVALUE_DROPTWOHANDEDITEM":                           13,
		"RETURNVALUE_BOTHHANDSNEEDTOBEFREE":                       14,
		"RETURNVALUE_CANONLYUSEONEWEAPON":                         15,
		"RETURNVALUE_NEEDEXCHANGE":                                16,
		"RETURNVALUE_CANNOTBEDRESSED":                             17,
		"RETURNVALUE_PUTTHISOBJECTINYOURHAND":                     18,
		"RETURNVALUE_PUTTHISOBJECTINBOTHHANDS":                    19,
		"RETURNVALUE_TOOFARAWAY":                                  20,
		"RETURNVALUE_FIRSTGODOWNSTAIRS":                           21,
		"RETURNVALUE_FIRSTGOUPSTAIRS":                             22,
		"RETURNVALUE_CONTAINERNOTENOUGHROOM":                      23,
		"RETURNVALUE_ONLYAMMOINQUIVER":                            24,
		"RETURNVALUE_NOTENOUGHCAPACITY":                           25,
		"RETURNVALUE_CANNOTPICKUP":                                26,
		"RETURNVALUE_THISISIMPOSSIBLE":                            27,
		"RETURNVALUE_DEPOTISFULL":                                 28,
		"RETURNVALUE_CONTAINERISFULL":                             29,
		"RETURNVALUE_CREATUREDOESNOTEXIST":                        30,
		"RETURNVALUE_CANNOTUSETHISOBJECT":                         31,
		"RETURNVALUE_PLAYERWITHTHISNAMEISNOTONLINE":               32,
		"RETURNVALUE_NOTREQUIREDLEVELTOUSERUNE":                   33,
		"RETURNVALUE_YOUAREALREADYTRADING":                        34,
		"RETURNVALUE_THISPLAYERISALREADYTRADING":                  35,
		"RETURNVALUE_YOUMAYNOTLOGOUTDURINGAFIGHT":                 36,
		"RETURNVALUE_DIRECTPLAYERSHOOT":                           37,
		"RETURNVALUE_NOTENOUGHLEVEL":                              38,
		"RETURNVALUE_NOTENOUGHMAGICLEVEL":                         39,
		"RETURNVALUE_NOTENOUGHMANA":                               40,
		"RETURNVALUE_NOTENOUGHSOUL":                               41,
		"RETURNVALUE_YOUAREEXHAUSTED":                             42,
		"RETURNVALUE_YOUCANNOTUSEOBJECTSTHATFAST":                 43,
		"RETURNVALUE_PLAYERISNOTREACHABLE":                        44,
		"RETURNVALUE_CANONLYUSETHISRUNEONCREATURES":               45,
		"RETURNVALUE_ACTIONNOTPERMITTEDINPROTECTIONZONE":          46,
		"RETURNVALUE_YOUMAYNOTATTACKTHISPLAYER":                   47,
		"RETURNVALUE_YOUMAYNOTATTACKAPERSONINPROTECTIONZONE":      48,
		"RETURNVALUE_YOUMAYNOTATTACKAPERSONWHILEINPROTECTIONZONE": 49,
		"RETURNVALUE_YOUMAYNOTATTACKTHISCREATURE":                 50,
		"RETURNVALUE_YOUCANONLYUSEITONCREATURES":                  51,
		"RETURNVALUE_CREATUREISNOTREACHABLE":                      52,
		"RETURNVALUE_TURNSECUREMODETOATTACKUNMARKEDPLAYERS":       53,
		"RETURNVALUE_YOUNEEDPREMIUMACCOUNT":                       54,
		"RETURNVALUE_YOUNEEDTOLEARNTHISSPELL":                     55,
		"RETURNVALUE_YOURVOCATIONCANNOTUSETHISSPELL":              56,
		"RETURNVALUE_YOUNEEDAWEAPONTOUSETHISSPELL":                57,
		"RETURNVALUE_PLAYERISPZLOCKEDLEAVEPVPZONE":                58,
		"RETURNVALUE_PLAYERISPZLOCKEDENTERPVPZONE":                59,
		"RETURNVALUE_ACTIONNOTPERMITTEDINANOPVPZONE":              60,
		"RETURNVALUE_YOUCANNOTLOGOUTHERE":                         61,
		"RETURNVALUE_YOUNEEDAMAGICITEMTOCASTSPELL":                62,
		"RETURNVALUE_CANNOTCONJUREITEMHERE":                       63,
		"RETURNVALUE_YOUNEEDTOSPLITYOURSPEARS":                    64,
		"RETURNVALUE_NAMEISTOOAMBIGUOUS":                          65,
		"RETURNVALUE_CANONLYUSEONESHIELD":                         66,
		"RETURNVALUE_NOPARTYMEMBERSINRANGE":                       67,
		"RETURNVALUE_YOUARENOTTHEOWNER":                           68,
		"RETURNVALUE_YOUCANTOPENCORPSEADM":                        69,
		"RETURNVALUE_NOSUCHRAIDEXISTS":                            70,
		"RETURNVALUE_ANOTHERRAIDISALREADYEXECUTING":               71,
		"RETURNVALUE_TRADEPLAYERFARAWAY":                          72,
		"RETURNVALUE_YOUDONTOWNTHISHOUSE":                         73,
		"RETURNVALUE_TRADEPLAYERALREADYOWNSAHOUSE":                74,
		"RETURNVALUE_TRADEPLAYERHIGHESTBIDDER":                    75,
		"RETURNVALUE_YOUCANNOTTRADETHISHOUSE":                     76,
		"RETURNVALUE_YOUDONTHAVEREQUIREDPROFESSION":               77,
		"RETURNVALUE_NOTENOUGHFISTLEVEL":                          78,
		"RETURNVALUE_NOTENOUGHCLUBLEVEL":                          79,
		"RETURNVALUE_NOTENOUGHSWORDLEVEL":                         80,
		"RETURNVALUE_NOTENOUGHAXELEVEL":                           81,
		"RETURNVALUE_NOTENOUGHDISTANCELEVEL":                      82,
		"RETURNVALUE_NOTENOUGHSHIELDLEVEL":                        83,
		"RETURNVALUE_NOTENOUGHFISHLEVEL":                          84,
		"RETURNVALUE_REWARDCHESTISEMPTY":                          85,
		"RETURNVALUE_REWARDCONTAINERISEMPTY":                      86,
		"RETURNVALUE_CONTACTADMINISTRATOR":                        87,
		"RETURNVALUE_ITEMISNOTYOURS":                              88,
		"RETURNVALUE_ITEMUNTRADEABLE":                             89,

		// Condition types
		"CONDITION_NONE":         0,
		"CONDITION_POISON":       1,
		"CONDITION_FIRE":         2,
		"CONDITION_ENERGY":       3,
		"CONDITION_BLEEDING":     4,
		"CONDITION_HASTE":        5,
		"CONDITION_PARALYZE":     6,
		"CONDITION_OUTFIT":       7,
		"CONDITION_INVISIBLE":    8,
		"CONDITION_LIGHT":        9,
		"CONDITION_MANASHIELD":   10,
		"CONDITION_INFIGHT":      11,
		"CONDITION_DRUNK":        12,
		"CONDITION_EXHAUST":      13,
		"CONDITION_REGENERATION": 14,
		// Condition slot ids (ConditionId_t). Food scripts pass CONDITIONID_DEFAULT.
		"CONDITIONID_DEFAULT": -1,
		"CONDITIONID_COMBAT":  0,
		// Sound effect used by the food action; sound playback is a no-op stub
		// for now, but the constant must exist so the script doesn't pass nil.
		"SOUND_EFFECT_TYPE_ACTION_EAT": 2803,
		"CONDITION_SOUL":               15,
		"CONDITION_DROWN":              16,
		"CONDITION_MUTED":              17,
		"CONDITION_CHANNELMUTEDTICKS":  18,
		"CONDITION_YELLTICKS":          19,
		"CONDITION_ATTRIBUTES":         20,
		"CONDITION_FREEZING":           21,
		"CONDITION_DAZZLED":            22,
		"CONDITION_CURSED":             23,

		"FORGE_NORMAL_MONSTER":     0,
		"FORGE_INFLUENCED_MONSTER": 1,
		"FORGE_FIENDISH_MONSTER":   2,

		// Bosstiary rarities (monster.bosstiary.bossRace). Match bosstiary.Rarity.
		"RARITY_BANE":    0,
		"RARITY_ARCHFOE": 1,
		"RARITY_NEMESIS": 2,

		// Charm categories (charmCategory_t) and types (charm_t), used by
		// data/scripts/systems/bestiary_charms.lua. Match internal/charms.
		"CHARM_ALL":       0,
		"CHARM_MAJOR":     1,
		"CHARM_MINOR":     2,
		"CHARM_UNDEFINED": 0,
		"CHARM_OFFENSIVE": 1,
		"CHARM_DEFENSIVE": 2,
		"CHARM_PASSIVE":   3,

		// Cylinder index / flags (src/items/cylinder.hpp, items_definitions.hpp).
		// Used by addItemEx / internalAddItem (e.g. Player:addItemStoreInbox).
		"INDEX_WHEREEVER":          -1,
		"FLAG_NOLIMIT":             1,
		"FLAG_IGNOREBLOCKITEM":     2,
		"FLAG_IGNOREBLOCKCREATURE": 4,
		"FLAG_CHILDISOWNER":        8,
		"FLAG_PATHFINDING":         16,
		"FLAG_IGNOREFIELDDAMAGE":   32,
		"FLAG_IGNORENOTMOVABLE":    64,
		"FLAG_IGNOREAUTOSTACK":     128,
		"FLAG_DROPONMAP":           256,
		"FLAG_LOOTPOUCH":           512,

		// Weapon types (WeaponType_t)
		"WEAPON_NONE":     0,
		"WEAPON_SWORD":    1,
		"WEAPON_CLUB":     2,
		"WEAPON_AXE":      3,
		"WEAPON_SHIELD":   4,
		"WEAPON_DISTANCE": 5,
		"WEAPON_WAND":     6,
		"WEAPON_AMMO":     7,
		"WEAPON_MISSILE":  8,
		"WEAPON_FIST":     9,

		// Ammo types (Ammo_t)
		"AMMO_NONE":          0,
		"AMMO_BOLT":          1,
		"AMMO_ARROW":         2,
		"AMMO_SPEAR":         3,
		"AMMO_THROWINGSTAR":  4,
		"AMMO_THROWINGKNIFE": 5,
		"AMMO_STONE":         6,
		"AMMO_SNOWBALL":      7,
	}

	for k, v := range enums {
		L.SetGlobal(k, v)
	}

	// The rest of what lua_enums.cpp registers, generated from the C++ enum
	// bodies. Applied after the hand-written table, which it never overlaps:
	// the generator refuses names already defined here.
	for k, v := range generatedEnums {
		L.SetGlobal(k, v)
	}

	registerSpellEnums(L)
}
