-- Canary-Go PostgreSQL schema (converted from the MySQL schema.sql).
-- Focused on the tables needed to authenticate and enter the world; extend as
-- more of the C++ persistence layer is ported.
--
-- Conversion notes vs MySQL:
--   AUTO_INCREMENT      -> GENERATED ... AS IDENTITY
--   int(11)/tinyint/... -> INTEGER/SMALLINT/BIGINT (display widths dropped)
--   UNSIGNED            -> widened type (BIGINT) or CHECK
--   mediumblob/blob     -> BYTEA
--   ENGINE=/CHARSET=    -> removed
--   INDEX inside table  -> separate CREATE INDEX
--   ON UPDATE CURRENT_TIMESTAMP -> trigger (omitted here)

BEGIN;

CREATE TABLE IF NOT EXISTS accounts (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(32) NOT NULL UNIQUE,
    password           VARCHAR(255) NOT NULL,
    email              VARCHAR(255) NOT NULL DEFAULT '',
    premdays           INTEGER NOT NULL DEFAULT 0,
    premdays_purchased INTEGER NOT NULL DEFAULT 0,
    lastday            BIGINT NOT NULL DEFAULT 0,
    type               SMALLINT NOT NULL DEFAULT 1,
    coins              BIGINT NOT NULL DEFAULT 0,
    coins_transferable BIGINT NOT NULL DEFAULT 0,
    tournament_coins   BIGINT NOT NULL DEFAULT 0,
    creation           BIGINT NOT NULL DEFAULT 0,
    recruiter          INTEGER NOT NULL DEFAULT 0,
    house_bid_id       INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_accounts_email ON accounts (email);

CREATE TABLE IF NOT EXISTS players (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL UNIQUE,
    group_id      INTEGER NOT NULL DEFAULT 1,
    account_id    INTEGER NOT NULL DEFAULT 0
                     REFERENCES accounts (id) ON DELETE CASCADE,
    level         INTEGER NOT NULL DEFAULT 1,
    vocation      INTEGER NOT NULL DEFAULT 0,
    health        INTEGER NOT NULL DEFAULT 150,
    healthmax     INTEGER NOT NULL DEFAULT 150,
    experience    BIGINT NOT NULL DEFAULT 0,
    lookbody      INTEGER NOT NULL DEFAULT 0,
    lookfeet      INTEGER NOT NULL DEFAULT 0,
    lookhead      INTEGER NOT NULL DEFAULT 0,
    looklegs      INTEGER NOT NULL DEFAULT 0,
    looktype      INTEGER NOT NULL DEFAULT 136,
    lookaddons    INTEGER NOT NULL DEFAULT 0,
    lookmount     INTEGER NOT NULL DEFAULT 0,
    maglevel      INTEGER NOT NULL DEFAULT 0,
    mana          INTEGER NOT NULL DEFAULT 0,
    manamax       INTEGER NOT NULL DEFAULT 0,
    manaspent     BIGINT NOT NULL DEFAULT 0,
    soul          INTEGER NOT NULL DEFAULT 0,
    town_id       INTEGER NOT NULL DEFAULT 1,
    posx          INTEGER NOT NULL DEFAULT 0,
    posy          INTEGER NOT NULL DEFAULT 0,
    posz          INTEGER NOT NULL DEFAULT 0,
    conditions    BYTEA,
    cap           INTEGER NOT NULL DEFAULT 400,
    sex           INTEGER NOT NULL DEFAULT 0,
    pronoun       INTEGER NOT NULL DEFAULT 0,
    lastlogin     BIGINT NOT NULL DEFAULT 0,
    lastip        BIGINT NOT NULL DEFAULT 0,
    save          SMALLINT NOT NULL DEFAULT 1,
    skull         SMALLINT NOT NULL DEFAULT 0,
    skulltime     BIGINT NOT NULL DEFAULT 0,
    lastlogout    BIGINT NOT NULL DEFAULT 0,
    blessings     SMALLINT NOT NULL DEFAULT 0,
    onlinetime    INTEGER NOT NULL DEFAULT 0,
    deletion      BIGINT NOT NULL DEFAULT 0,
    balance       BIGINT NOT NULL DEFAULT 0,
    stamina       INTEGER NOT NULL DEFAULT 2520,
    skill_fist       INTEGER NOT NULL DEFAULT 10,
    skill_fist_tries      BIGINT NOT NULL DEFAULT 0,
    skill_club       INTEGER NOT NULL DEFAULT 10,
    skill_club_tries      BIGINT NOT NULL DEFAULT 0,
    skill_sword      INTEGER NOT NULL DEFAULT 10,
    skill_sword_tries     BIGINT NOT NULL DEFAULT 0,
    skill_axe        INTEGER NOT NULL DEFAULT 10,
    skill_axe_tries       BIGINT NOT NULL DEFAULT 0,
    skill_dist       INTEGER NOT NULL DEFAULT 10,
    skill_dist_tries      BIGINT NOT NULL DEFAULT 0,
    skill_shielding  INTEGER NOT NULL DEFAULT 10,
    skill_shielding_tries BIGINT NOT NULL DEFAULT 0,
    skill_fishing    INTEGER NOT NULL DEFAULT 10,
    skill_fishing_tries   BIGINT NOT NULL DEFAULT 0,
    comment       VARCHAR(255) NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_players_account ON players (account_id);
CREATE INDEX IF NOT EXISTS idx_players_vocation ON players (vocation);

-- Per-player Lua storage key/value.
CREATE TABLE IF NOT EXISTS player_storage (
    player_id INTEGER NOT NULL REFERENCES players (id) ON DELETE CASCADE,
    key       INTEGER NOT NULL DEFAULT 0,
    value     INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (player_id, key)
);

-- Server-wide Lua storage key/value.
CREATE TABLE IF NOT EXISTS global_storage (
    key   INTEGER NOT NULL PRIMARY KEY,
    value INTEGER NOT NULL DEFAULT 0
);

-- Inventory / container items (OTBR attribute blob).
CREATE TABLE IF NOT EXISTS player_items (
    player_id  INTEGER NOT NULL REFERENCES players (id) ON DELETE CASCADE,
    pid        INTEGER NOT NULL DEFAULT 0,
    sid        INTEGER NOT NULL DEFAULT 0,
    itemtype   INTEGER NOT NULL DEFAULT 0,
    count      INTEGER NOT NULL DEFAULT 0,
    attributes BYTEA,
    PRIMARY KEY (player_id, sid)
);

-- Learned instant spells.
CREATE TABLE IF NOT EXISTS player_spells (
    player_id INTEGER NOT NULL REFERENCES players (id) ON DELETE CASCADE,
    name      VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS players_online (
    player_id INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS account_sessions (
    id         VARCHAR(191) NOT NULL PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    expires    BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS towns (
    id    INTEGER NOT NULL PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    posx  INTEGER NOT NULL DEFAULT 0,
    posy  INTEGER NOT NULL DEFAULT 0,
    posz  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS server_config (
    config VARCHAR(50) NOT NULL PRIMARY KEY,
    value  VARCHAR(256) NOT NULL DEFAULT ''
);

-- Async job queue processed via LISTEN/NOTIFY (see internal/db/jobs.go).
CREATE TABLE IF NOT EXISTS async_jobs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       VARCHAR(64) NOT NULL,
    payload    JSONB NOT NULL DEFAULT '{}'::jsonb,
    status     VARCHAR(16) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_async_jobs_status ON async_jobs (status);

-- Notify listeners whenever a job is enqueued.
CREATE OR REPLACE FUNCTION async_jobs_notify() RETURNS trigger AS $$
BEGIN
    PERFORM pg_notify('async_jobs', NEW.id::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS async_jobs_notify_trg ON async_jobs;
CREATE TRIGGER async_jobs_notify_trg
    AFTER INSERT ON async_jobs
    FOR EACH ROW EXECUTE FUNCTION async_jobs_notify();

INSERT INTO towns (id, name, posx, posy, posz)
VALUES (1, 'Thais', 1000, 1000, 7)
ON CONFLICT (id) DO NOTHING;

INSERT INTO server_config (config, value) VALUES ('db_version', '1')
ON CONFLICT (config) DO NOTHING;

COMMIT;
